/**
 * Provides immutable, structural tuple types for holding a fixed number of potentially
 * heterogeneous elements.
 *
 * <p>This package includes the sealed interface {@link org.higherkindedj.hkt.tuple.Tuple} and its
 * concrete record implementations from {@link org.higherkindedj.hkt.tuple.Tuple2} to {@code
 * Tuple12}. {@code Tuple2} through {@code Tuple5} are hand-written; {@code Tuple6} through {@code
 * Tuple12} are generated by the {@code hkj-processor} annotation processor. These are primarily
 * used by the for-comprehension builder in the {@code hkt.expression} package to accumulate results
 * from monadic steps.
 */
@NullMarked
package org.higherkindedj.hkt.tuple;

import org.jspecify.annotations.NullMarked;
