plugins {
  `java-library`
  id("com.vanniktech.maven.publish")
}

dependencies {
  // Bring in the autoconfigure module
  api(project(":hkj-spring:autoconfigure"))

  // Client-side HTTP integration (@HkjHttpClient runtime + translators + decoder)
  api(project(":hkj-spring:client"))

  // Spring Boot starter web (provides Spring MVC, Tomcat, Jackson)
  api(libs.spring.boot.starter.web)

  // HTTP Service Client auto-configuration: binds spring.http.serviceclient.<group>.* and applies
  // the base URL/timeouts to the @ImportHttpServices groups generated by @HkjHttpClient. Not pulled
  // in by spring-boot-starter-web, so consumers of the @HkjHttpClient client need it explicitly.
  api(libs.spring.boot.restclient)

  // Annotation processors for generating optics and @HkjHttpClient clients
  annotationProcessor(project(":hkj-processor"))
  annotationProcessor(project(":hkj-processor-plugins"))
  annotationProcessor(project(":hkj-spring:client-processor"))
}

mavenPublishing {
  publishToMavenCentral()
  signAllPublications()

  coordinates(
    groupId = project.group.toString(),
    artifactId = "hkj-spring-boot-starter",
    version = project.version.toString()
  )

  pom {
    name.set("Higher-Kinded-J Spring Boot Starter")
    description.set("Spring Boot starter for Higher-Kinded-J - Functional programming patterns for Spring applications")
    url.set("https://github.com/higher-kinded-j/higher-kinded-j")

    licenses {
      license {
        name.set("The MIT License")
        url.set("https://opensource.org/licenses/MIT")
      }
    }
    developers {
      developer {
        id.set("higher-kinded-j")
        name.set("Magnus Smith")
        email.set("simulation-hkt@gmail.com")
      }
    }
    scm {
      connection.set("scm:git:git://github.com/higher-kinded-j/higher-kinded-j.git")
      developerConnection.set("scm:git:ssh://github.com/higher-kinded-j/higher-kinded-j.git")
      url.set("https://github.com/higher-kinded-j/higher-kinded-j")
    }
    inceptionYear.set("2025")
    organization {
      name.set("The Higher-Kinded-J Team")
      url.set("https://github.com/higher-kinded-j")
    }
    issueManagement {
      system.set("GitHub")
      url.set("https://github.com/higher-kinded-j/higher-kinded-j/issues")
    }
  }
}
