// Copyright (c) 2025 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.optics.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks code elements as generated by Higher-Kinded-J annotation processors.
 *
 * <p>This annotation is applied to classes, methods, and constructors that are automatically
 * generated during compilation by Higher-Kinded-J's optics generation system (e.g., {@link
 * GenerateLenses}, {@link GeneratePrisms}).
 *
 * <h2>Purpose</h2>
 *
 * <ul>
 *   <li><b>IDE Integration:</b> Helps IDEs distinguish generated code from hand-written code
 *   <li><b>Code Coverage:</b> Allows coverage tools to exclude generated code from metrics
 *   <li><b>Static Analysis:</b> Enables linters and analysers to skip generated code
 *   <li><b>Developer Clarity:</b> Clearly identifies code that shouldn't be manually edited
 * </ul>
 *
 * <h2>Retention Policy</h2>
 *
 * <p>Uses {@link RetentionPolicy#CLASS} rather than {@code SOURCE} or {@code RUNTIME}:
 *
 * <ul>
 *   <li><b>Preserved in bytecode:</b> Available to bytecode analysers and tools
 *   <li><b>Not runtime overhead:</b> Not loaded into memory at runtime (unlike {@code RUNTIME})
 *   <li><b>Tooling support:</b> Accessible to static analysis tools operating on compiled classes
 * </ul>
 *
 * <h2>Usage in Higher-Kinded-J</h2>
 *
 * <p>When you annotate a record with {@code @GenerateLenses}:
 *
 * <pre>{@code
 * @GenerateLenses
 * public record User(String name, int age) {}
 * }</pre>
 *
 * <p>The annotation processor generates a {@code UserLenses} class:
 *
 * <pre>{@code
 * @Generated  // <- Applied here
 * public final class UserLenses {
 *
 *     @Generated  // <- And on each generated method
 *     public static Lens<User, String> name() { ... }
 *
 *     @Generated
 *     public static Lens<User, Integer> age() { ... }
 *
 *     @Generated  // <- And on generated constructors
 *     private UserLenses() {}
 * }
 * }</pre>
 *
 * <h2>Comparison to {@code javax.annotation.Generated}</h2>
 *
 * <p>Higher-Kinded-J defines its own {@code @Generated} annotation rather than using {@code
 * javax.annotation.Generated} (JDK 9+) or {@code javax.annotation.processing.Generated} (JDK 8)
 * for several reasons:
 *
 * <ul>
 *   <li><b>Java 8 compatibility:</b> Avoids dependency on JDK 9+ APIs
 *   <li><b>Module system:</b> Avoids issues with {@code java.annotation} module visibility
 *   <li><b>Simplicity:</b> Tailored to Higher-Kinded-J's specific needs without extra metadata
 * </ul>
 *
 * <h2>Best Practices</h2>
 *
 * <ul>
 *   <li><b>Never apply manually:</b> This annotation is exclusively for annotation processors
 *   <li><b>Don't edit generated code:</b> Changes will be overwritten on next compilation
 *   <li><b>Configure coverage tools:</b> Exclude {@code @Generated} classes from coverage reports
 *   <li><b>IDE integration:</b> Modern IDEs use this annotation to visually distinguish generated
 *       code
 * </ul>
 *
 * @see GenerateLenses
 * @see GeneratePrisms
 * @since 1.0
 */
@Retention(RetentionPolicy.CLASS)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.CONSTRUCTOR})
public @interface Generated {}
