// Copyright (c) 2025 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.optics.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks code elements as generated by Higher-Kinded-J annotation processors.
 *
 * <p>This annotation is applied to classes, methods, and constructors that are automatically
 * generated during compilation by Higher-Kinded-J's optics generation system (e.g., {@link
 * GenerateLenses}, {@link GeneratePrisms}).
 *
 * <h2>Purpose</h2>
 *
 * <ul>
 *   <li><b>IDE Integration:</b> Helps IDEs distinguish generated code from hand-written code
 *   <li><b>Code Coverage:</b> Allows coverage tools to exclude generated code from metrics
 *   <li><b>Static Analysis:</b> Enables linters and analysers to skip generated code
 *   <li><b>Developer Clarity:</b> Clearly identifies code that shouldn't be manually edited
 * </ul>
 *
 */
@Retention(RetentionPolicy.CLASS)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.CONSTRUCTOR})
public @interface Generated {}
