// Copyright (c) 2025 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.article2.domain;

import org.higherkindedj.article2.optics.Lens;

/**
 * An address with street, city, and postcode.
 *
 * <p>In production with Higher-Kinded-J, you would annotate this with {@code @GenerateLenses} to
 * auto-generate the lens accessors.
 */
public record Address(String street, String city, String postcode) {

  /**
   * Lens accessors for Address fields.
   *
   * <p>These would be auto-generated by {@code @GenerateLenses} in production.
   */
  public static final class Lenses {
    private Lenses() {}

    public static Lens<Address, String> street() {
      return Lens.of(
          Address::street,
          (newStreet, addr) -> new Address(newStreet, addr.city(), addr.postcode()));
    }

    public static Lens<Address, String> city() {
      return Lens.of(
          Address::city, (newCity, addr) -> new Address(addr.street(), newCity, addr.postcode()));
    }

    public static Lens<Address, String> postcode() {
      return Lens.of(
          Address::postcode,
          (newPostcode, addr) -> new Address(addr.street(), addr.city(), newPostcode));
    }
  }
}
