// Copyright (c) 2025 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.article2.domain;

import org.higherkindedj.article2.optics.Lens;
import org.higherkindedj.article2.optics.Prism;

/**
 * A sealed interface representing different shapes.
 *
 * <p>This demonstrates prisms for sum types. In production with Higher-Kinded-J, you would annotate
 * this with {@code @GeneratePrisms} to auto-generate the prism accessors.
 */
public sealed interface Shape permits Shape.Circle, Shape.Rectangle, Shape.Triangle {

  /** A circle with a radius. */
  record Circle(double radius) implements Shape {
    /** Lens accessors for Circle. */
    public static final class Lenses {
      private Lenses() {}

      public static Lens<Circle, Double> radius() {
        return Lens.of(Circle::radius, (r, _) -> new Circle(r));
      }
    }
  }

  /** A rectangle with width and height. */
  record Rectangle(double width, double height) implements Shape {
    /** Lens accessors for Rectangle. */
    public static final class Lenses {
      private Lenses() {}

      public static Lens<Rectangle, Double> width() {
        return Lens.of(Rectangle::width, (w, rect) -> new Rectangle(w, rect.height()));
      }

      public static Lens<Rectangle, Double> height() {
        return Lens.of(Rectangle::height, (h, rect) -> new Rectangle(rect.width(), h));
      }
    }
  }

  /** A triangle with three sides. */
  record Triangle(double a, double b, double c) implements Shape {
    /** Lens accessors for Triangle. */
    public static final class Lenses {
      private Lenses() {}

      public static Lens<Triangle, Double> a() {
        return Lens.of(Triangle::a, (newA, tri) -> new Triangle(newA, tri.b(), tri.c()));
      }

      public static Lens<Triangle, Double> b() {
        return Lens.of(Triangle::b, (newB, tri) -> new Triangle(tri.a(), newB, tri.c()));
      }

      public static Lens<Triangle, Double> c() {
        return Lens.of(Triangle::c, (newC, tri) -> new Triangle(tri.a(), tri.b(), newC));
      }
    }
  }

  /**
   * Prism accessors for Shape variants.
   *
   * <p>These would be auto-generated by {@code @GeneratePrisms} in production.
   */
  final class Prisms {
    private Prisms() {}

    public static Prism<Shape, Circle> circle() {
      return Prism.of(
          shape ->
              shape instanceof Circle c ? java.util.Optional.of(c) : java.util.Optional.empty(),
          c -> c);
    }

    public static Prism<Shape, Rectangle> rectangle() {
      return Prism.of(
          shape ->
              shape instanceof Rectangle r ? java.util.Optional.of(r) : java.util.Optional.empty(),
          r -> r);
    }

    public static Prism<Shape, Triangle> triangle() {
      return Prism.of(
          shape ->
              shape instanceof Triangle t ? java.util.Optional.of(t) : java.util.Optional.empty(),
          t -> t);
    }
  }

  /** Calculate the area of this shape. */
  default double area() {
    return switch (this) {
      case Circle(var r) -> Math.PI * r * r;
      case Rectangle(var w, var h) -> w * h;
      case Triangle(var a, var b, var c) -> {
        // Heron's formula
        double s = (a + b + c) / 2;
        yield Math.sqrt(s * (s - a) * (s - b) * (s - c));
      }
    };
  }
}
