// Copyright (c) 2025 - 2026 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
/**
 * Open-arity accumulating assembly: build a value from N independently validated fields, collecting
 * <b>all</b> errors, with no {@code Semigroup} argument, no arity wall, and no {@code Kind}
 * ceremony.
 *
 * <p>Two entry flavours exist on each of three carriers ({@link
 * org.higherkindedj.hkt.validated.Validated}, {@link org.higherkindedj.hkt.effect.ValidationPath}
 * via {@link org.higherkindedj.hkt.effect.Path}, and {@link
 * org.higherkindedj.hkt.eitherorboth.EitherOrBoth}):
 *
 * <ul>
 *   <li>{@code accumulate()} — generic in the error payload {@code X}, carried as {@code
 *       NonEmptyList<X>}; fields join with {@code and(value)}.
 *   <li>{@code fields()} — the error channel is fixed to {@code NonEmptyList<}{@link
 *       org.higherkindedj.hkt.assembly.FieldError}{@code >}; {@code field(label, value)} prepends
 *       the label onto each error's path, so nested assemblies compose (for example {@code
 *       "address.zip"}).
 * </ul>
 *
 * <pre>{@code
 * Validated<NonEmptyList<FieldError>, User> user =
 *     Validated.fields()
 *         .field("name", Name.parse(dto.name()))
 *         .field("email", Email.parse(dto.email()))
 *         .field("age", Age.parse(dto.age()))
 *         .apply(User::new);
 * }</pre>
 *
 * <p>Errors always accumulate in <b>field-declaration order</b>. The staged types ({@code
 * ValidatedAccum1..12} and friends) are generated by the annotation processor; only the arity-0
 * entry stages and {@code FieldError} are hand-written. Records with more than twelve fields nest a
 * sub-record per slot.
 */
@NullMarked
@GenerateAccumulators(minArity = 1, maxArity = 12)
package org.higherkindedj.hkt.assembly;

import org.higherkindedj.optics.annotations.GenerateAccumulators;
import org.jspecify.annotations.NullMarked;
