// Copyright (c) 2025 - 2026 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.example.effect;

import java.util.List;
import org.higherkindedj.hkt.effect.ReaderPath;
import org.higherkindedj.optics.Lens;
import org.higherkindedj.optics.annotations.GenerateFocus;
import org.higherkindedj.optics.focus.FocusPath;

/**
 * Demonstrates {@code ReaderPath.magnify(FocusPath)} in a service-layer shape close to a Spring
 * application.
 *
 * <p>The pattern: each sub-service is written against a typed sub-environment ({@code DbConfig},
 * {@code AuthConfig}). The application bundles those into a larger {@code AppEnv}, and the
 * controller-level code lifts the sub-services into {@code AppEnv}-shaped requests using {@code
 * magnify(FocusPath)}, where the {@link FocusPath} comes from {@code @GenerateFocus} without any
 * boilerplate.
 *
 * <p>This is the same shape a Spring service layer takes when typed dependencies are injected via
 * {@link ReaderPath} rather than constructor parameters. The win is that each sub-service stays
 * narrowly typed against its dependency, and the wider environment shape is composed at the call
 * site.
 *
 * <p>Run with:
 *
 * <pre>{@code
 * ./gradlew :hkj-examples:run -PmainClass=org.higherkindedj.example.effect.MagnifyServiceLayerExample
 * }</pre>
 */
public class MagnifyServiceLayerExample {

  // ============= Domain Model =============

  @GenerateFocus
  public record DbConfig(String url, int maxConnections) {}

  @GenerateFocus
  public record AuthConfig(String issuer, int tokenTtlSeconds) {}

  /** The bundled application environment exposed to controller-level code. */
  @GenerateFocus
  public record AppEnv(DbConfig db, AuthConfig auth, String tenant) {}

  public record User(String id, String name, String tenant) {}

  // ============= Sub-services (narrow typing) =============

  /** Loads a user. Knows only about {@link DbConfig}. */
  static ReaderPath<DbConfig, User> loadUser(String userId) {
    return ReaderPath.asks(
        db -> {
          // Pretend we open a connection and look up the user.
          System.out.println(
              "[db] using " + db.url() + " (pool=" + db.maxConnections() + ") to load " + userId);
          return new User(userId, "Alice " + userId, "tenant-X");
        });
  }

  /** Issues a token. Knows only about {@link AuthConfig}. */
  static ReaderPath<AuthConfig, String> issueToken(String userId) {
    return ReaderPath.asks(
        auth -> {
          System.out.println(
              "[auth] issuer=" + auth.issuer() + " ttl=" + auth.tokenTtlSeconds() + "s");
          return "token-" + userId + "@" + auth.issuer();
        });
  }

  // ============= Controller-level composition =============

  /**
   * Builds a controller-level computation: load the user, then issue a token, both lifted into the
   * larger {@link AppEnv} via {@code magnify(FocusPath)}.
   *
   * <p>This is what an HTTP handler would look like when its dependencies are read from the
   * environment rather than injected by name.
   */
  static ReaderPath<AppEnv, String> handleLogin(String userId) {
    // The two sub-services use different sub-environments. Lift them both
    // into AppEnv via the FocusPath instances generated by @GenerateFocus.
    FocusPath<AppEnv, DbConfig> dbPath = AppEnvFocus.db();
    FocusPath<AppEnv, AuthConfig> authPath = AppEnvFocus.auth();

    ReaderPath<AppEnv, User> appLoadUser = loadUser(userId).magnify(dbPath);
    ReaderPath<AppEnv, String> appIssueToken = issueToken(userId).magnify(authPath);

    // Combine: load the user, then issue the token. The composition reads
    // a single environment (AppEnv) but the sub-services never had to.
    return appLoadUser.via(user -> appIssueToken.map(token -> user.name() + " -> " + token));
  }

  // ============= Demonstration =============

  public static void main(String[] args) {
    System.out.println("=== ReaderPath.magnify(FocusPath): Service-Layer Reader-as-DI ===\n");

    AppEnv production =
        new AppEnv(
            new DbConfig("jdbc:postgresql://prod.example/app", 50),
            new AuthConfig("auth.example.com", 3600),
            "acme");

    AppEnv staging =
        new AppEnv(
            new DbConfig("jdbc:postgresql://staging.example/app", 5),
            new AuthConfig("auth-staging.example.com", 60),
            "acme-staging");

    System.out.println("--- production environment ---");
    String resultProd = handleLogin("u-42").run(production);
    System.out.println("result: " + resultProd);

    System.out.println("\n--- staging environment ---");
    String resultStaging = handleLogin("u-42").run(staging);
    System.out.println("result: " + resultStaging);

    System.out.println("\n--- escape hatch: local(Function) for non-optic adaptation ---");
    // The bare-Function form remains available for environment shapes that
    // are not naturally expressed as optics. Same operation, different idiom.
    ReaderPath<AppEnv, User> viaLocal = loadUser("u-99").local(AppEnv::db);
    User u = viaLocal.run(production);
    System.out.println("loaded via local(Function): " + u);

    System.out.println("\n--- composition across multiple environment layers ---");
    // Wrap AppEnv in a per-request shell and lift again. magnify chains.
    record RequestContext(AppEnv app, String requestId) {}
    ReaderPath<RequestContext, String> requestHandler =
        handleLogin("u-1")
            .magnify(
                FocusPath.of(
                    Lens.of(
                        RequestContext::app,
                        (ctx, env) -> new RequestContext(env, ctx.requestId()))));
    String layered = requestHandler.run(new RequestContext(production, "req-" + System.nanoTime()));
    System.out.println("layered: " + layered);

    System.out.println("\nServices ran against narrowly-typed sub-environments.");
    System.out.println("Composition happened at the call site via magnify(FocusPath).");

    // Quiet unused-variable warning in the demo.
    System.out.println(
        "\n(Tenants seen: "
            + List.of(production.tenant(), staging.tenant()).stream()
                .reduce((a, b) -> a + ", " + b)
                .orElse("(none)")
            + ")");
  }
}
