// Copyright (c) 2025 - 2026 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.optics.processing;

import static com.google.testing.compile.Compiler.javac;
import static org.assertj.core.api.Assertions.assertThat;

import com.google.testing.compile.Compilation;
import com.google.testing.compile.JavaFileObjects;
import java.io.IOException;
import java.util.Optional;
import javax.tools.JavaFileObject;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

/**
 * Structural validation tests for {@link CoupledLensGenerator}.
 *
 * <p>Exercises the generator by compiling test fixtures and asserting on the structure of the
 * single {@code CoupledLenses} file it emits.
 */
@DisplayName("CoupledLensGenerator Tests")
class CoupledLensGeneratorTest {

  private static final String GENERATED_CLASS = "org.higherkindedj.optics.util.CoupledLenses";

  private static JavaFileObject packageInfoSource(int min, int max) {
    return JavaFileObjects.forSourceString(
        "org.higherkindedj.hkt.expression.package-info",
        """
        @GenerateForComprehensions(minArity = %d, maxArity = %d)
        package org.higherkindedj.hkt.expression;

        import org.higherkindedj.optics.annotations.GenerateForComprehensions;
        """
            .formatted(min, max));
  }

  private Compilation compile(JavaFileObject source) {
    return javac().withProcessors(new ForComprehensionProcessor()).compile(source);
  }

  private String getGeneratedSource(Compilation compilation) throws IOException {
    Optional<JavaFileObject> file = compilation.generatedSourceFile(GENERATED_CLASS);
    assertThat(file).as("Generated file should exist: %s", GENERATED_CLASS).isPresent();
    return file.get().getCharContent(true).toString();
  }

  @Nested
  @DisplayName("File-level structure")
  class FileStructure {

    @Test
    @DisplayName("class is declared in optics.util with @Generated, final, private ctor")
    void classDeclaration() throws IOException {
      String source = getGeneratedSource(compile(packageInfoSource(2, 9)));

      assertThat(source).contains("// Generated by hkj-processor. Do not edit.");
      assertThat(source).contains("package org.higherkindedj.optics.util;");
      assertThat(source).contains("@Generated");
      assertThat(source).contains("public final class CoupledLenses {");
      assertThat(source).contains("private CoupledLenses() {}");
    }

    @Test
    @DisplayName("imports cover the Function and Tuple arities used")
    void importsAreComplete() throws IOException {
      String source = getGeneratedSource(compile(packageInfoSource(2, 9)));

      assertThat(source).contains("import org.higherkindedj.optics.Lens;");
      assertThat(source).contains("import org.higherkindedj.optics.annotations.Generated;");
      // Simple form for arity 3 imports Function3; preserving form imports Function4.
      assertThat(source).contains("import org.higherkindedj.hkt.function.Function3;");
      assertThat(source).contains("import org.higherkindedj.hkt.function.Function4;");
      // Preserving form for arity 9 imports Function10.
      assertThat(source).contains("import org.higherkindedj.hkt.function.Function10;");
      // Tuples used: 3 and 9.
      assertThat(source).contains("import org.higherkindedj.hkt.tuple.Tuple3;");
      assertThat(source).contains("import org.higherkindedj.hkt.tuple.Tuple9;");
    }

    @Test
    @DisplayName("Function imports start at effectiveMin: a narrowed range omits lower arities")
    void importsTrackEffectiveMin() throws IOException {
      // Range 5..9 means coupled5..coupled9; Function imports must start at 5 (not 3).
      // Function3 / Function4 should not appear (would be unused imports).
      String source = getGeneratedSource(compile(packageInfoSource(5, 9)));

      assertThat(source).doesNotContain("import org.higherkindedj.hkt.function.Function3;");
      assertThat(source).doesNotContain("import org.higherkindedj.hkt.function.Function4;");
      assertThat(source).contains("import org.higherkindedj.hkt.function.Function5;");
      assertThat(source).contains("import org.higherkindedj.hkt.function.Function10;");
    }
  }

  @Nested
  @DisplayName("Per-arity methods")
  class PerArity {

    @Test
    @DisplayName("coupled3 has both overloads with correct signatures and body")
    void coupled3Shape() throws IOException {
      String source = getGeneratedSource(compile(packageInfoSource(2, 9)));

      // Preserving form: takes Function4<S, A, B, C, S>
      assertThat(source)
          .contains(
              "public static <S, A, B, C> Lens<S, Tuple3<A, B, C>> coupled3(\n"
                  + "      Lens<S, A> first,\n"
                  + "      Lens<S, B> second,\n"
                  + "      Lens<S, C> third,\n"
                  + "      Function4<S, A, B, C, S> reconstructor)");
      // Reads all three lenses to build a Tuple3.
      assertThat(source).contains("new Tuple3<>(first.get(s), second.get(s), third.get(s))");
      // Applies the reconstructor with the source + all three tuple elements.
      assertThat(source).contains("reconstructor.apply(s, tuple._1(), tuple._2(), tuple._3())");

      // Simple form: takes Function3<A, B, C, S>
      assertThat(source).contains("Function3<A, B, C, S> constructor");
      // Simple form delegates to the preserving form, dropping the source.
      assertThat(source)
          .contains(
              "return coupled3(first, second, third, "
                  + "(s, firstValue, secondValue, thirdValue) "
                  + "-> constructor.apply(firstValue, secondValue, thirdValue));");
    }

    @Test
    @DisplayName("coupled5 has both overloads with the right type parameters")
    void coupled5Shape() throws IOException {
      String source = getGeneratedSource(compile(packageInfoSource(2, 9)));

      assertThat(source)
          .contains("public static <S, A, B, C, D, E> Lens<S, Tuple5<A, B, C, D, E>> coupled5(");
      assertThat(source).contains("Function6<S, A, B, C, D, E, S> reconstructor");
      assertThat(source).contains("Function5<A, B, C, D, E, S> constructor");
    }

    @Test
    @DisplayName("coupled9 is the top of the ladder")
    void coupled9Shape() throws IOException {
      String source = getGeneratedSource(compile(packageInfoSource(2, 9)));

      assertThat(source)
          .contains(
              "public static <S, A, B, C, D, E, F, G, H, I> "
                  + "Lens<S, Tuple9<A, B, C, D, E, F, G, H, I>> coupled9(");
      assertThat(source).contains("Function10<S, A, B, C, D, E, F, G, H, I, S> reconstructor");
    }

    @Test
    @DisplayName("the ladder runs 3 through 9, twice each (preserving + simple)")
    void fullLadder() throws IOException {
      String source = getGeneratedSource(compile(packageInfoSource(2, 9)));

      for (int n = 3; n <= 9; n++) {
        final String marker = "coupled" + n + "(";
        // Declarations live on lines starting with the public-static modifier; the inner
        // delegation call from the simple form would otherwise inflate the count.
        long declarations =
            source
                .lines()
                .filter(line -> line.startsWith("  public static"))
                .filter(line -> line.contains(marker))
                .count();
        assertThat(declarations)
            .as("coupled%d should be declared twice (preserving + simple)", n)
            .isEqualTo(2);
      }
    }
  }

  @Nested
  @DisplayName("Arity clamping")
  class Clamping {

    @Test
    @DisplayName("requested range below 3 emits no CoupledLenses (binary is Lens.paired)")
    void belowLadderEmitsNothing() {
      Compilation compilation = compile(packageInfoSource(2, 2));
      assertThat(compilation.generatedSourceFile(GENERATED_CLASS)).isEmpty();
    }

    @Test
    @DisplayName("requested range overlapping ladder yields only the overlap")
    void overlapOnlyEmitsRange() throws IOException {
      String source = getGeneratedSource(compile(packageInfoSource(2, 4)));

      assertThat(source).contains(" coupled3(");
      assertThat(source).contains(" coupled4(");
      // The ladder starts at 3; even though the request covers 2, coupled2 must not be generated
      // (the binary case is Lens.paired). This locks in the MIN_SUPPORTED_ARITY clamp.
      assertThat(source).doesNotContain(" coupled2(");
      assertThat(source).doesNotContain(" coupled5(");
      assertThat(source).doesNotContain(" coupled9(");
    }

    @Test
    @DisplayName("single-arity range emits exactly that arity")
    void singleArityEmits() throws IOException {
      // Locks in the `effectiveMin > effectiveMax` boundary: with min=max=3 the early-return
      // branch must not fire.
      String source = getGeneratedSource(compile(packageInfoSource(3, 3)));
      assertThat(source).contains(" coupled3(");
      assertThat(source).doesNotContain(" coupled4(");
    }

    @Test
    @DisplayName("requested range above ladder cap clamps to 9")
    void aboveLadderCapClamps() throws IOException {
      String source = getGeneratedSource(compile(packageInfoSource(8, 12)));

      assertThat(source).contains(" coupled8(");
      assertThat(source).contains(" coupled9(");
      // Past the cap: not present, even though maxArity was 12.
      assertThat(source).doesNotContain(" coupled10(");
      assertThat(source).doesNotContain(" coupled11(");
      assertThat(source).doesNotContain(" coupled12(");
    }
  }
}
