// Copyright (c) 2025 - 2026 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.optics.processing;

import static com.google.testing.compile.CompilationSubject.assertThat;
import static com.google.testing.compile.Compiler.javac;
import static org.higherkindedj.optics.processing.GeneratorTestHelper.assertGeneratedCodeContains;

import com.google.testing.compile.JavaFileObjects;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

public class LensProcessorIntegrationTest {

  @Test
  void shouldGenerateLensesAndWitherMethodsForRecord() {
    final var sourceFile =
        JavaFileObjects.forSourceString(
            "com.example.User",
            """
            package com.example;

            import org.higherkindedj.optics.annotations.GenerateLenses;
            import org.higherkindedj.optics.Lens; // Ensure Lens is imported

            @GenerateLenses
            public record User(String name, int age) {}
            """);

    // THE FIX: Expect simple names (e.g., "Lens", "User", "String") as generated by JavaPoet,
    // because it will add the necessary import statements.
    final String expectedNameLens =
        """
        public static Lens<User, String> name() {
            return Lens.of(User::name, (source, newValue) -> new User(newValue, source.age()));
        }
        """;
    final String expectedAgeLens =
        """
        public static Lens<User, Integer> age() {
            return Lens.of(User::age, (source, newValue) -> new User(source.name(), newValue));
        }
        """;

    // THE FIX: Also expect simple names and the correct argument order in the `set` method call.
    final String expectedWithName =
        """
        public static User withName(User source, String newName) {
            return name().set(newName, source);
        }
        """;
    final String expectedWithAge =
        """
        public static User withAge(User source, int newAge) {
            return age().set(newAge, source);
        }
        """;

    var compilation = javac().withProcessors(new LensProcessor()).compile(sourceFile);

    assertThat(compilation).succeeded();

    final String generatedClassName = "com.example.UserLenses";
    assertGeneratedCodeContains(compilation, generatedClassName, expectedNameLens);
    assertGeneratedCodeContains(compilation, generatedClassName, expectedAgeLens);
    assertGeneratedCodeContains(compilation, generatedClassName, expectedWithName);
    assertGeneratedCodeContains(compilation, generatedClassName, expectedWithAge);
  }

  @Test
  @DisplayName("a raw component and a raw type-parameter bound compile under -Werror")
  void rawComponentAndRawBoundCompileUnderWerror() {
    // The lens and with methods restate the component type and redeclare the record's type
    // parameters with their bounds, in a file the author's own suppression does not reach.
    var raw =
        JavaFileObjects.forSourceString(
            "com.example.RawBag",
            """
            package com.example;
            import java.util.List;
            import java.util.Optional;
            import org.higherkindedj.optics.annotations.GenerateLenses;
            @GenerateLenses
            @SuppressWarnings("rawtypes")
            public record RawBag(List tags, Optional<List> contacts) {}
            """);
    var bounded =
        JavaFileObjects.forSourceString(
            "com.example.BoundedBag",
            """
            package com.example;
            import java.util.List;
            import org.higherkindedj.optics.annotations.GenerateLenses;
            @GenerateLenses
            @SuppressWarnings("rawtypes")
            public record BoundedBag<T extends List>(T value, String id) {}
            """);
    var compilation =
        javac()
            .withProcessors(new LensProcessor())
            .withOptions("-Xlint:unchecked,rawtypes", "-Werror")
            .compile(raw, bounded);

    assertThat(compilation).succeededWithoutWarnings();
    assertGeneratedCodeContains(
        compilation,
        "com.example.RawBagLenses",
        "@SuppressWarnings(\"rawtypes\") public static Lens<RawBag, List> tags()");
  }
}
