// Copyright (c) 2025 - 2026 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.checker;

import java.util.Optional;

/**
 * Centralised error message formatting for the HKJ checker.
 *
 * <p>This class provides consistent error messages across all check sites. Messages follow the
 * pattern: describe what was expected, what was received, and how to fix it.
 */
public final class DiagnosticMessages {

  private DiagnosticMessages() {}

  /** Base URL for the published Higher-Kinded-J documentation. */
  static final String DOCS_BASE = "https://higher-kinded-j.github.io/latest/";

  /**
   * Appends a documentation pointer to a diagnostic message.
   *
   * <p>The page is linked rather than a heading fragment: the book's section anchors are
   * auto-generated by mdBook from heading text and change whenever a heading is reworded, so a
   * fragment would rot. The relevant page is short enough that the page-level link is sufficient.
   *
   * @param message the diagnostic message to extend
   * @param relativePath the documentation path relative to {@link #DOCS_BASE} (e.g.
   *     "effect/compiler_errors.html")
   * @return the message with a trailing " See: &lt;url&gt;" pointer
   */
  static String withDocLink(String message, String relativePath) {
    return message + " See: " + DOCS_BASE + relativePath;
  }

  /**
   * Formats a Path type mismatch error message.
   *
   * @param methodName the method where the mismatch was detected (e.g., "via", "zipWith")
   * @param expectedType the simple name of the expected Path type (e.g., "MaybePath")
   * @param actualType the simple name of the actual Path type (e.g., "IOPath")
   * @return a formatted error message
   */
  public static String pathTypeMismatch(String methodName, String expectedType, String actualType) {
    String base =
        "Path type mismatch in %s(): expected %s but received %s. "
                .formatted(methodName, expectedType, actualType)
            + "Each Path type can only chain with the same type.";

    Optional<String> conversion = PathTypeRegistry.suggestedConversion(actualType, expectedType);
    String body =
        conversion.isPresent()
            ? base + " Use conversion methods like " + conversion.get() + " to convert."
            : base + " Use conversion methods (toEitherPath, toMaybePath, etc.) to change types.";
    return withDocLink(body, "effect/compiler_errors.html");
  }

  /**
   * Formats the companion diagnostic for a transformer monad constructed with no arguments.
   *
   * <p>Every transformer monad needs the outer {@code Monad<F>} instance (and {@code WriterTMonad}
   * additionally a {@code Monoid<W>}); the constructor cannot infer it. Emitted alongside javac's
   * own "constructor cannot be applied to given types" error.
   *
   * @param simpleName the transformer monad class simple name (e.g. "EitherTMonad")
   * @return a formatted error message
   */
  public static String transformerMissingMonad(String simpleName) {
    boolean writerT = "WriterTMonad".equals(simpleName);
    String example =
        writerT
            ? "new WriterTMonad<>(someOuterMonad, outputMonoid)"
            : "new %s<>(someOuterMonad)".formatted(simpleName);
    String body =
        "%s needs the outer Monad<F> instance, e.g. %s. ".formatted(simpleName, example)
            + "Every transformer wraps an outer effect and cannot infer it"
            + (writerT ? "; WriterTMonad also needs a Monoid<W> for the accumulated output." : ".");
    return withDocLink(body, "transformers/common_errors.html");
  }

  /**
   * Formats the companion diagnostic for a {@code switch} over {@code Free} that omits the {@code
   * HandleError} and/or {@code Ap} variants.
   *
   * <p>{@code Free} is a sealed type with variants {@code Pure}, {@code Suspend}, {@code
   * FlatMapped}, {@code HandleError} and {@code Ap}. An interpreter that pattern-matches the older
   * three but not the error-handling/applicative variants is no longer exhaustive once those are
   * used. (No documentation link: this consolidates the {@code AddHandleErrorCaseRecipe}
   * OpenRewrite diagnosis, which has no companion doc chapter.)
   *
   * @param missingHandleError whether the {@code HandleError} case is absent
   * @param missingAp whether the {@code Ap} case is absent
   * @return a formatted error message
   */
  public static String freeSwitchMissingCases(boolean missingHandleError, boolean missingAp) {
    String missing =
        (missingHandleError && missingAp)
            ? "Free.HandleError and Free.Ap cases"
            : missingHandleError ? "Free.HandleError case" : "Free.Ap case";
    return "This switch over Free is missing the %s. Free has variants Pure, Suspend, FlatMapped, "
            .formatted(missing)
        + "HandleError (error recovery) and Ap (applicative); an interpreter must handle them all.";
  }

  /**
   * Formats the diagnostic for a lazy effect built then discarded as a bare statement.
   *
   * <p>Effects ({@code Path}/{@code IO}/{@code Free} and the rest of the {@code Chainable}
   * hierarchy) are deferred values: composing one and not assigning, returning, or running it does
   * nothing at all. There is no javac error here — the code type-checks — so without this check the
   * no-op is entirely silent.
   *
   * @param typeName the discarded effect's simple type name (e.g. "EitherPath")
   * @return a formatted error message
   */
  public static String discardedEffect(String typeName) {
    String body =
        ("This %s is built but never used: effects are lazy and do nothing until run. "
                + "Assign it, return it, pass it on, or run it (e.g. unsafeRun()/an interpreter) — "
                + "as a bare statement it is a silent no-op.")
            .formatted(typeName);
    return withDocLink(body, "effect/capabilities.html");
  }

  /**
   * Formats the companion diagnostic for {@code StateT.mapT} called without the leading {@code
   * Monad<G>}.
   *
   * <p>{@code StateT} is the only transformer whose {@code mapT} takes the target monad as an extra
   * first argument (the state-threading function must close over the new monad). {@code
   * EitherT}/{@code OptionalT}/{@code MaybeT}/{@code ReaderT}/{@code WriterT.mapT} take just the
   * function, which is why this mistake is so easy to make. Emitted alongside javac's own "method
   * mapT cannot be applied to given types" error.
   *
   * @return a formatted error message
   */
  public static String stateTMapTArity() {
    String body =
        "StateT.mapT(...) needs the target Monad<G> as its first argument, e.g. "
            + "stateT.mapT(targetMonad, f). StateT is the only transformer whose mapT takes this "
            + "extra argument — EitherT/OptionalT/MaybeT/ReaderT/WriterT.mapT take just the "
            + "function.";
    return withDocLink(body, "transformers/common_errors.html");
  }

  /**
   * Formats the diagnostic for a silently-erased error-type mismatch in an error-typed Path chain.
   *
   * <p>{@code via}/{@code flatMap}/{@code then}/{@code zipWith} bind the next step to {@code
   * Chainable<B>}, which does not carry the error type. A step whose error type {@code E} differs
   * from the receiver's therefore compiles, and the wrong {@code E} is carried at runtime (latent
   * {@code ClassCastException} when the error is consumed). There is no javac error here — without
   * this check the mismatch is entirely silent.
   *
   * @param methodName the chain method (e.g. "via")
   * @param receiverE the receiver's error type, simple name
   * @param stepE the offending step's error type, simple name
   * @return a formatted message
   */
  public static String errorTypeMismatch(String methodName, String receiverE, String stepE) {
    String body =
        ("Error type is silently mismatched in %s(): the chain carries E=%s but this step yields "
                + "E=%s, which is not assignable to %s. The chain erases E through Chainable<B>, so "
                + "the wrong error type is carried at runtime (latent ClassCastException). Use the "
                + "same error type across the chain, or mapError at the boundary.")
            .formatted(methodName, receiverE, stepE, receiverE);
    return withDocLink(body, "effect/compiler_errors.html");
  }

  /**
   * Formats the companion diagnostic for {@code value()} called on a bare {@code Kind}.
   *
   * <p>{@code org.higherkindedj.hkt.Kind} is an empty marker interface; {@code value()} lives on
   * the concrete transformer ({@code EitherT}/{@code OptionalT}/{@code MaybeT}/{@code ReaderT}/
   * {@code StateT}/{@code WriterT}). Emitted alongside javac's own "cannot find symbol" error.
   *
   * @return a formatted error message
   */
  public static String kindValueNarrow() {
    String body =
        "value() is defined on the concrete transformer (EitherT/OptionalT/MaybeT/ReaderT/StateT/"
            + "WriterT), not on Kind. Narrow first, e.g. EITHER_T.narrow(kind).value(), or declare "
            + "the variable as the concrete transformer type.";
    return withDocLink(body, "transformers/common_errors.html");
  }

  /**
   * Formats the companion diagnostic for a higher-kinded witness that does not satisfy {@code
   * WitnessArity}.
   *
   * <p>{@code Kind}/{@code Kind2}/{@code Monad}/{@code Functor}/{@code Applicative} all require
   * their witness to be {@code WitnessArity}-bounded. Emitted alongside javac's own "type argument
   * … is not within bounds" error.
   *
   * @param typeVariable whether the offending witness is an (unbounded) type parameter rather than
   *     a concrete class
   * @param witnessName the witness type's name
   * @return a formatted error message
   */
  public static String witnessArity(boolean typeVariable, String witnessName) {
    String body =
        typeVariable
            ? ("Type parameter %s is used as a higher-kinded witness but is not "
                    + "WitnessArity-bounded. Bound it: <%s extends WitnessArity<TypeArity.Unary>> "
                    + "(use TypeArity.Binary for Kind2).")
                .formatted(witnessName, witnessName)
            : ("%s is used as a higher-kinded witness but does not implement WitnessArity. Add "
                    + "'implements WitnessArity<TypeArity.Unary>' (use TypeArity.Binary for Kind2).")
                .formatted(witnessName);
    return body;
  }

  /**
   * Formats the companion diagnostic for {@code via}/{@code flatMap}/{@code then} given a function
   * that returns a plain value instead of a {@code Chainable} ({@code effect/compiler_errors.md}
   * section 3).
   *
   * <p>{@code via} is the Path equivalent of {@code flatMap}: the function must return a Path. A
   * function returning a plain {@code B} should be passed to {@code map} instead. Emitted alongside
   * javac's own "method … cannot be applied" error.
   *
   * @param methodName the chain method (e.g. "via")
   * @param returnTypeName the (non-Path) return type's simple name
   * @return a formatted error message
   */
  public static String viaNonPath(String methodName, String returnTypeName) {
    String body =
        ("%s() needs a function that returns a Path, but this one returns %s. For a plain "
                + "transformation use map() instead; use %s() only when the function itself "
                + "returns a Path.")
            .formatted(methodName, returnTypeName, methodName);
    return withDocLink(body, "effect/compiler_errors.html");
  }

  /**
   * Formats the diagnostic for {@code map} given a function that returns the same Path type,
   * silently nesting the effect.
   *
   * <p>{@code map} is the functor map ({@code A -> B}); a function returning a {@code Path} makes
   * {@code B} itself a {@code Path}, so the result is {@code Path<Path<…>>}. This compiles — there
   * is no javac error — so without this check the nesting is silent. The user almost always meant
   * {@code via} ({@code flatMap}).
   *
   * @param pathType the (nested) Path type's simple name
   * @return a formatted message
   */
  public static String mapNestsEffect(String pathType) {
    String body =
        ("map() here nests the effect: the function returns %s, so the result is a %s of %s. "
                + "map() is for plain A->B transformations; to chain a Path-returning function use "
                + "via() (the Path flatMap) instead.")
            .formatted(pathType, pathType, pathType);
    return withDocLink(body, "effect/compiler_errors.html");
  }

  /**
   * Formats the advisory nudge for direct raw {@code Free} construction.
   *
   * <p>This is valid code, not an error — the nudge points at the more ergonomic, type-safe {@code
   * FreePath} fluent API / generated {@code *Ops} smart constructors. Consolidates the {@code
   * ConvertRawFreeToFreePathRecipe} OpenRewrite recipe.
   *
   * @param method the invoked {@code Free} factory ("liftF" or "suspend")
   * @return a formatted message
   */
  public static String rawFreeConstruction(String method) {
    return ("Free.%s(...) works, but the FreePath fluent API or the generated *Ops smart "
            + "constructors are more ergonomic and type-safe for composing Free programs.")
        .formatted(method);
  }

  /**
   * Formats the advisory nudge for manual {@code InjectInstances} boilerplate.
   *
   * <p>Valid code, not an error — the nudge points at {@code @ComposeEffects} and its generated
   * Support class, which removes the boilerplate and ensures correct {@code EitherF} nesting.
   * Consolidates the {@code DetectInjectBoilerplateRecipe} OpenRewrite recipe.
   *
   * @param method the invoked factory ("injectLeft"/"injectRight"/"injectRightThen")
   * @return a formatted message
   */
  public static String injectBoilerplate(String method) {
    return ("InjectInstances.%s(...) works, but @ComposeEffects with its generated Support class "
            + "removes this boilerplate and ensures correct EitherF nesting.")
        .formatted(method);
  }
}
