// Copyright (c) 2025 - 2026 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.example.market.model;

import java.time.Instant;
import java.util.Objects;
import org.higherkindedj.example.market.model.value.Symbol;

/**
 * An alert generated by anomaly detection.
 *
 * @param symbol the affected symbol
 * @param severity the alert severity
 * @param message a human-readable description
 * @param timestamp when the alert was generated
 */
public record Alert(Symbol symbol, Severity severity, String message, Instant timestamp) {
  public Alert {
    Objects.requireNonNull(symbol, "symbol must not be null");
    Objects.requireNonNull(severity, "severity must not be null");
    Objects.requireNonNull(message, "message must not be null");
    Objects.requireNonNull(timestamp, "timestamp must not be null");
  }

  public enum Severity {
    INFO,
    WARNING,
    CRITICAL
  }
}
