// Copyright (c) 2025 - 2026 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation to mark code that should be excluded from JaCoCo coverage analysis.
 *
 * <p>JaCoCo automatically excludes code annotated with annotations that have "Generated" in their
 * name. This annotation is used to mark:
 *
 * <ul>
 *   <li>Code generated by annotation processors
 *   <li>Defensive code that is unreachable in normal usage due to Java's sealed interface mechanism
 *   <li>Other code that should be excluded from coverage metrics
 * </ul>
 *
 * <p>Example usage for sealed interface defensive checks:
 *
 * <pre>{@code
 * @Generated("sealed-interface-defensive-check")
 * private static void throwUnreachableError() {
 *     throw new IllegalArgumentException("This code is unreachable");
 * }
 * }</pre>
 *
 * <p>Example usage for generated code:
 *
 * <pre>{@code
 * @Generated("optics-processor")
 * public Lens<Person, String> nameLens() { ... }
 * }</pre>
 */
@Documented
@Retention(RetentionPolicy.CLASS)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.CONSTRUCTOR})
public @interface Generated {
  /**
   * A description of why this code is excluded from coverage, or the name of the generator that
   * produced the code.
   *
   * @return the reason for exclusion or generator name
   */
  String value() default "";
}
