@startuml cf_kind
!include https://raw.githubusercontent.com/ncosta-ic/catppuccin-macchiato-plantuml-theme/main/theme.puml
hide empty members

interface Kind<F, A> <<HKT Bridge>>

interface CompletableFutureKind<A> extends Kind<CompletableFutureKind.Witness, A> {
  ' Witness F = CompletableFutureKind<?>
}

class "CompletableFuture<A>" {
  ' Standard Java Class
}


  class CompletableFutureKindHelper {
    + {static} Kind<CompletableFutureKind.Witness, A> widen(@NonNull CompletableFuture<A>)
    + {static} @NonNull CompletableFuture<A> narrow(@Nullable Kind<CompletableFutureKind<?>, A>)
    + {static} A join(Kind<CompletableFutureKind<?>, A>)
    ' ...
  }

  class CompletableFutureHolder<A> implements CompletableFutureKind<A> {
    - @NonNull CompletableFuture<A> future
  }

  CompletableFutureKindHelper ..> CompletableFutureHolder : creates
  CompletableFutureKindHelper ..> "CompletableFuture<A>" : narrows to / widens from
  CompletableFutureHolder o--> "CompletableFuture<A>" : holds


@enduml