@startuml cf_monad
!include https://raw.githubusercontent.com/ncosta-ic/catppuccin-macchiato-plantuml-theme/main/theme.puml
hide empty members

note "F extends WitnessArity<TypeArity.Unary>\nfor all type classes" as ArityNote

class CompletableFutureKindHelper {}

class CompletableFutureFunctor implements Functor<CompletableFutureKind.Witness> {
 + Kind<CFK, B> map(Function<A, B>, Kind<CFK, A>) ' CFK = CompletableFutureKind.Witness
}
CompletableFutureFunctor ..> CompletableFutureKindHelper : uses

class CompletableFutureApplicative extends CompletableFutureFunctor implements Applicative<CompletableFutureKind.Witness> {
  + Kind<CFK, A> of(A)
  + Kind<CFK, B> ap(Kind<CFK, Function<A, B>>, Kind<CFK, A>)
}

class CompletableFutureMonad extends CompletableFutureApplicative implements MonadError<CompletableFutureKind.Witness, Throwable> {
 + Kind<CFK, B> flatMap(Function<A, Kind<CFK, B>>, Kind<CFK, A>)
 + Kind<CFK, A> raiseError(Throwable)
 + Kind<CFK, A> handleErrorWith(Kind<CFK, A>, Function<Throwable, Kind<CFK, A>>)
}



@enduml