@startuml core_typeclasses

!include https://raw.githubusercontent.com/ncosta-ic/catppuccin-macchiato-plantuml-theme/main/theme.puml


package "HKT Core - Type Classes" {
    interface "Kind<F extends WitnessArity<?>, A>" as Kind {
      ' F is the phantom type (e.g., XKind.Witness)
      ' A is the value type
    }

    interface "WitnessArity<A extends TypeArity>" as WitnessArity {
      ' Marker interface for arity classification
    }

    enum "TypeArity" as TypeArity {
      Unary
      Binary
    }

    interface "Functor<F extends WitnessArity<Unary>>" as Functor {
        + map(fn: Function<A,B>, fa: Kind<F,A>) : Kind<F,B>
    }
    interface "Applicative<F extends WitnessArity<Unary>>" as Applicative {
        + of(value: A) : Kind<F,A>
        + ap(ff: Kind<F, Function<A,B>>, fa: Kind<F,A>) : Kind<F,B>
        ' mapN methods can be shown if desired, but are often defaults
        ' + map2(Kind<F,A>, Kind<F,B>, BiFunction<A,B,C>) : Kind<F,C>
    }
    interface "Monad<F extends WitnessArity<Unary>>" as Monad {
        + flatMap(fn: Function<A, Kind<F,B>>, ma: Kind<F,A>) : Kind<F,B>
    }
    interface "MonadError<F extends WitnessArity<Unary>, E>" as MonadError {
        + raiseError(error: E) : Kind<F,A>
        + handleErrorWith(ma: Kind<F,A>, handler: Function<E, Kind<F,A>>) : Kind<F,A>
        ' Other recovery methods can be shown if desired
    }

    interface "Semigroup<A>" as Semigroup {
        + combine(x: A, y: A) : A
    }

    interface "Monoid<A>" as Monoid {
        + empty() : A
    }

     interface "Traverse<T extends WitnessArity<Unary>>" as Traverse {
        + traverse(a: Applicative<G>, f : Function<A, Kind<G, B>>, ta : Kind<T, A>) : Kind<G, Kind<T, B>>
        + sequence(a: Applicative<G>, tga : Kind<T, Kind<G, A>>) : Kind<G, Kind<T, A>>
     }

    WitnessArity ..> TypeArity : parameterised by
    Kind ..> WitnessArity : F extends
    Functor ..> Kind : (operates on)
    Applicative --|> Functor
    Monad --|> Applicative
    MonadError --|> Monad
    Monoid --|> Semigroup
    Traverse --|> Functor

}
@enduml

