@startuml defunctionalisation_internal

!include https://raw.githubusercontent.com/ncosta-ic/catppuccin-macchiato-plantuml-theme/main/theme.puml
hide empty members

package "Defunctionalisation Pattern For Library-Defined Types (Id, Maybe, IO, Transformers)" {


    interface "IdKind<A>" as IdKindInterface extends Kind<IdKind.Witness, A> {
        class Witness {} ' Nested phantom Witness type
    }
    ' Id<A> itself implements IdKind<A>
    class "Id<A>(value: A)" as IdRecord implements IdKindInterface {
    }
    IdRecord --|> IdKindInterface

    class "IdKindHelper" as IdKindHelper {
        + {static} widen(id: Id<A>): Kind<IdKind.Witness, A>
        + {static} narrow(kind: Kind<IdKind.Witness, A>): Id<A>
    }
    IdKindHelper ..> IdRecord : "casts to/from"

    class "IdentityMonad" as IdentityMonad implements Monad<IdKind.Witness> {
        ' Uses IdKindHelper
    }
    IdentityMonad ..> IdKindHelper : "uses"

}
@enduml

