@startuml
!theme plain
!include https://raw.githubusercontent.com/ncosta-ic/catppuccin-macchiato-plantuml-theme/main/theme.puml

title Either<L,R> Type Structure and HKT Integration


interface "Kind<F_WITNESS, A>" as Kind




  interface "Either<L, R>" as EitherInterface extends EitherKind<L,R> {
    + {static} Left<L,R> left(L value)
    + {static} Right<L,R> right(R value)
    + boolean isLeft()
    + boolean isRight()
    + L getLeft() throws NoSuchElementException
    + R getRight() throws NoSuchElementException
    + <U> U fold(Function<L,U> leftMapper, Function<R,U> rightMapper)
    + <RR> Either<L,RR> map(Function<R,RR> mapper)
    + <RR> Either<L,RR> flatMap(Function<R, Either<L,RR>> mapper)
  }

  package "internal implementations" {
    class "Left<L, R>" as LeftRecord <<record>> implements Either<L,R> {
    + Left(L value)
     }
    class "Right<L, R>" as RightRecord <<record>>  implements Either<L,R> {
    + Right(R value)
         }
  }
  Either <|-- LeftRecord
  Either <|-- RightRecord


  class EitherKindHelper {
    + {static} wrap(either: Either<L,R>): Kind<EitherKind.Witness<L>, R>
    + {static} unwrap(kind: Kind<EitherKind.Witness<L>, R>): Either<L,R>
    + {static} left(monad: MonadError<F,L>, error: L): Kind<F,R> ' This is more for EitherT.left
    + {static} right(monad: Monad<F>, value: R): Kind<F,R>      ' This is more for EitherT.right
  }
  note right of EitherKindHelper::wrap
    `wrap` effectively casts `Either` to `Kind`
    as `Either` directly implements `EitherKind`.
  end note
  note right of EitherKindHelper::unwrap
    `unwrap` checks `instanceof Either` and casts.
  end note

  EitherKindHelper ..> "Either<L, R>" : "casts to/from"

EitherKind --|> Kind


@enduml
