@startuml free_kind

!include https://raw.githubusercontent.com/ncosta-ic/catppuccin-macchiato-plantuml-theme/main/theme.puml


hide empty members

note "Witness<F> implements\nWitnessArity<TypeArity.Unary>" as WitnessNote

interface "Kind<F extends WitnessArity<?>, A>" <<interface>>

interface "FreeKind<F, A>" <<interface>>

class "FreeKindHelper" <<enum>> {
  + {static} Kind<FreeKind.Witness<F>, A> widen(Free<F, A> free)
  + {static} Free<F, A> narrow(Kind<FreeKind.Witness<F>, A> kind)
}

interface "Free<F, A>" <<sealed interface>> {
  + <B> Free<F, B> map(Function<? super A, ? extends B> f)
  + <B> Free<F, B> flatMap(Function<A, Free<F, B>> f)
  + <M> Kind<M, A> foldMap(...)
}

"FreeKind<F, A>" -up-|> "Kind<F, A>" : <<FreeKind.Witness<F>, A>>
"FreeKindHelper" ..> "Free<F, A>" : widens/narrows
"FreeKindHelper" ..> "FreeKind<F, A>" : widens/narrows

@enduml
