@startuml id_monad
!include https://raw.githubusercontent.com/ncosta-ic/catppuccin-macchiato-plantuml-theme/main/theme.puml


hide empty members


interface "Kind<F, A>" as Kind {}
interface "Functor<M>" as FunctorBase {}
interface "Applicative<M>" as ApplicativeBase {}
interface "Monad<M>" as MonadBase {}


class "Id<A>" as Id << (R,orchid) Record >> {
}

class "IdKindHelper" as IdKindHelper << (H,grey) >> {
}

class IdentityMonad {
}

' --- Relationships ---

' HKT Interface Hierarchy
MonadBase --|> ApplicativeBase
ApplicativeBase --|> FunctorBase
FunctorBase --|> Kind


Id --|> Kind : <Id.Witness, A>


IdentityMonad ..|> MonadBase : <Id.Witness>

' Dependencies
IdentityMonad ..> IdKindHelper : uses narrow
IdentityMonad ..> Id : uses

IdKindHelper ..> Id : uses widen / narrow





@enduml