@startuml IO Components
!include https://raw.githubusercontent.com/ncosta-ic/catppuccin-macchiato-plantuml-theme/main/theme.puml

interface Supplier<T> {
  + T get()
}

interface IO<A> {
  + {abstract} A unsafeRunSync()
  + {static} IO<A> delay(Supplier<A>)
  + IO<B> map(Function<? super A, ? extends B>)
  + IO<B> flatMap(Function<? super A, ? extends IO<B>>)
}
IO ..> Supplier : uses >

interface Kind<F, A> <<HKT Bridge>> {
}

interface IOKind<A> extends Kind<IOKind.Witness, A> {
  ' HKT Marker for IO
  ' Witness F = IOKind.Witness
  ' Value Type A = A
}

package helper <<Rectangle>> {
  class IOKindHelper {
    .. Static Helper Methods ..
    + {static} IOKind<A> wrap(IO<A>)
    + {static} IO<A> unwrap(Kind<IOKind.Witness, A>)
    + {static} Kind<IOKind.Witness, A> delay(Supplier<A>)
    + {static} A unsafeRunSync(Kind<IOKind.Witness, A>)
  }

  ' Internal Holder Record
  class IOHolder<A> implements IOKind<A> {
    - IO<A> ioInstance
  }
  IOKindHelper ..> IOHolder : creates >
  IOKindHelper --> IO : uses >
  IOHolder o--> IO : holds
}


interface Functor<F>
interface "Applicative<F> extends Functor<F>"
interface "Monad<F> extends Applicative<F>"

class IOFunctor implements Functor<IOKind.Witness> {
 + Kind<IOKind.Witness, B> map(Function<A, B>, Kind<IOKind.Witness, A>)
}
IOFunctor ..> IOKindHelper : uses

class IOApplicative extends IOFunctor implements Applicative<IOKind.Witness> {
  + Kind<IOKind.Witness, A> of(A)
  + Kind<IOKind.Witness, B> ap(Kind<IOKind.Witness, Function<A, B>>, Kind<IOKind.Witness, A>)
}

class IOMonad extends IOApplicative implements Monad<IOKind.Witness> {
 + Kind<IOKind.Witness, B> flatMap(Function<A, Kind<IOKind.Witness, B>>, Kind<IOKind.Witness, A>)
}


@enduml