@startuml io_monad
!include https://raw.githubusercontent.com/ncosta-ic/catppuccin-macchiato-plantuml-theme/main/theme.puml
hide empty members

interface Functor<F> {
  + Kind<F, B> map(Function<A, B>, Kind<F, A>)
}
interface Applicative<F> extends Functor<F> {
  + Kind<F, A> of(A)
  + Kind<F, B> ap(Kind<F, Function<A, B>>, Kind<F, A>)
}
interface Monad<F> extends Applicative<F> {
  + Kind<F, B> flatMap(Function<A, Kind<F, B>>, Kind<F, A>)
}


class IOKindHelper {
 {static} Kind<IOKind.Witness, A> wrap(IO<A>)
 {static} IO<A> unwrap(Kind<IOKind.Witness, A>)
 ' ...
}

class IOFunctor implements Functor<IOKind.Witness> {
 + Kind<IOKind.Witness, B> map(Function<A, B>, Kind<IOKind.Witness, A>)
}
IOFunctor ..> IOKindHelper : uses

class IOApplicative extends IOFunctor implements Applicative<IOKind.Witness> {
  + Kind<IOKind.Witness, A> of(A)
  + Kind<IOKind.Witness, B> ap(Kind<IOKind.Witness, Function<A, B>>, Kind<IOKind.Witness, A>)
}

class IOMonad extends IOApplicative implements Monad<IOKind.Witness> {
 + Kind<IOKind.Witness, B> flatMap(Function<A, Kind<IOKind.Witness, B>>, Kind<IOKind.Witness, A>)
}

@enduml