@startuml maybe_monad
!include https://raw.githubusercontent.com/ncosta-ic/catppuccin-macchiato-plantuml-theme/main/theme.puml
hide empty members

interface "Kind<F, A>" as Kind
interface "Functor<F>" as Functor
interface "Applicative<F>" as Applicative
interface "Monad<M>" as MonadBase
interface "MonadError<M, E>" as MonadErrorBase


  interface "Maybe<T>" as MaybeInterface << (M,LightBlue) >> {
    + static <T> Maybe<T> just(T)
    + static <T> Maybe<T> nothing()
    + static <T> Maybe<T> fromNullable(T)
    + boolean isJust()
    + boolean isNothing()
    + T get()
    + T orElse(T)
    + T orElseGet(Supplier<T>)
    + Maybe<U> map(Function<T,U>)
    + Maybe<U> flatMap(Function<T,Maybe<U>>)
  }

  class "Just<T>" extends MaybeInterface {
    - T value
    + Just(T)
  }

  class "Nothing<T>" extends MaybeInterface {
    - static Nothing<?> INSTANCE
    + static <T> Nothing<T> instance()
  }

  interface "MaybeKind<A>" as MaybeKindBase << (K,LightSkyBlue) >> {
    ' Witness type for Maybe
  }

  class "MaybeKindHelper" as MaybeKindHelper << (H,grey) >> {
    ' Utility for MaybeKind
    ' + static <A> Maybe<A> unwrap(Kind<MaybeKind.Witness, A>)
    ' + static <A> MaybeKind<A> wrap(Maybe<A>)
    ' + static <A> Kind<MaybeKind.Witness,A> just(A)
    ' + static <A> Kind<MaybeKind.Witness,A> nothing()
  }
  note right of MaybeKindHelper
    Contains internal 'MaybeHolder<A> record'
    which implements MaybeKind<A>.
    `record MaybeHolder<A>(Maybe<A> maybe) implements MaybeKind<A> {}`
  end note


  class "MaybeFunctor" as MaybeFunctorImpl {
    ' + <A,B> MaybeKind<B> map(Function<A,B>, Kind<MaybeKind.Witness,A>)
  }

  class "MaybeMonad" as MaybeMonadImpl {
    ' + <A> MaybeKind<A> of(A)
    ' + <A,B> MaybeKind<B> flatMap(Function<A, Kind<MaybeKind.Witness,B>>, Kind<MaybeKind.Witness,A>)
    ' + <A,B> Kind<MaybeKind.Witness,B> ap(Kind<MaybeKind.Witness,Function<A,B>>, Kind<MaybeKind.Witness,A>)
    ' --- MonadError ---
    ' + <A> Kind<MaybeKind.Witness,A> raiseError(Void)
    ' + <A> Kind<MaybeKind.Witness,A> handleErrorWith(Kind<MaybeKind.Witness,A>, Function<Void, Kind<MaybeKind.Witness,A>>)
  }


MonadErrorBase --|> MonadBase
MonadBase --|> Applicative
Applicative --|> Functor
Functor --|> Kind

MaybeKindBase --|> Kind : <MaybeKind.Witness, A>

MaybeFunctorImpl ..|> Functor : <MaybeKind.Witness>
MaybeMonadImpl --|> MaybeFunctorImpl
MaybeMonadImpl ..|> MonadErrorBase : <MaybeKind.Witness, Void>

MaybeMonadImpl ..> MaybeKindHelper : uses
MaybeFunctorImpl ..> MaybeKindHelper : uses
MaybeKindHelper ..> MaybeInterface : uses (wrap/unwrap)
MaybeInterface <|.. Just
MaybeInterface <|.. Nothing

@enduml
