@startuml supported_types
!include https://raw.githubusercontent.com/ncosta-ic/catppuccin-macchiato-plantuml-theme/main/theme.puml
hide empty members

left to right direction

package "Supported Types (Monad Implementations)" {
    class ListMonad
    class StreamMonad
    class OptionalMonad
    class MaybeMonad
    class "EitherMonad<L>" as EitherMonad
    class CompletableFutureMonad
    class TryMonad
    class IOMonad
    class LazyMonad
    class IdMonad
    class "ReaderMonad<R>" as ReaderMonad
    class "StateMonad<S>" as StateMonad
    class "WriterMonad<W>" as WriterMonad
    class "ValidatedMonad<E>" as ValidatedMonad
    class TrampolineMonad
    class "FreeMonad<F>" as FreeMonad

    ListMonad <|.. CoreInterfaces.Monad
    StreamMonad <|.. CoreInterfaces.MonadZero
    OptionalMonad <|.. CoreInterfaces.MonadError
    MaybeMonad <|.. CoreInterfaces.MonadError
    EitherMonad <|.. CoreInterfaces.MonadError
    CompletableFutureMonad <|.. CoreInterfaces.MonadError
    TryMonad <|.. CoreInterfaces.MonadError
    ValidatedMonad <|.. CoreInterfaces.MonadError
    IdMonad <|.. CoreInterfaces.Monad
    IOMonad <|.. CoreInterfaces.Monad
    LazyMonad <|.. CoreInterfaces.Monad
    ReaderMonad <|.. CoreInterfaces.Monad
    StateMonad <|.. CoreInterfaces.Monad
    WriterMonad <|.. CoreInterfaces.Monad
    TrampolineMonad <|.. CoreInterfaces.Monad
    FreeMonad <|.. CoreInterfaces.Monad

    ' Example relation for Optional
    OptionalMonad ..> "Simulation Plumbing.OptionalKind" : operates on witness
}

'package "Bifunctor Implementations" {
'    class ConstBifunctor
'
'    ConstBifunctor <|.. CoreInterfaces.Bifunctor
'
'    note right of ConstBifunctor
'        Const<C, A> holds constant value C
'        with phantom type parameter A
'    end note
'}

@enduml