@startuml trampoline_kind
!include https://raw.githubusercontent.com/ncosta-ic/catppuccin-macchiato-plantuml-theme/main/theme.puml

hide empty members

note "Witness implements\nWitnessArity<TypeArity.Unary>" as WitnessNote

interface Kind<F extends WitnessArity<?>, A>

interface "TrampolineKind<A>" {
  {nested} class Witness implements WitnessArity<Unary>
}

class TrampolineKindHelper {
  + {static} Trampoline<A> narrow(Kind<TrampolineKind.Witness, A> kind)
  + {static} Kind<TrampolineKind.Witness, A> widen(Trampoline<A> trampoline)
  + {static} Kind<TrampolineKind.Witness, A> done(A value)
  + {static} Kind<TrampolineKind.Witness, A> defer(Supplier<Trampoline<A>> next)
  + {static} A run(Kind<TrampolineKind.Witness, A> kind)
}

interface "Trampoline<A>" <<sealed interface>> {
  + A run()
  + <B> Trampoline<B> map(Function<A, B> f)
  + <B> Trampoline<B> flatMap(Function<A, Trampoline<B>> f)
}

"Trampoline<A>" ..|> "TrampolineKind<A>" : implements
"TrampolineKind<A>" --|> Kind : <TrampolineKind.Witness, A>
TrampolineKindHelper ..> "Trampoline<A>" : widens/narrows
TrampolineKindHelper ..> "TrampolineKind<A>" : widens/narrows

@enduml
