plugins {
    `maven-publish`
    signing
    id("net.thebugmc.gradle.sonatype-central-portal-publisher") version "1.2.4"
}

dependencies {
    // Depends on the annotations module to find the @GenerateLenses annotation
    implementation(project(":hkj-core"))


    // The processor's own dependencies, which will not leak into the core module
    implementation("com.palantir.javapoet:javapoet:0.7.0")
    implementation("com.google.auto.service:auto-service-annotations:1.1.1")
    annotationProcessor("com.google.auto.service:auto-service:1.1.1")
}

val isSnapshotVersion: Boolean by rootProject.extra
val isReleaseBuild: Boolean by rootProject.extra

signing {
    isRequired = isReleaseBuild
    if (isReleaseBuild) {
        sign(publishing.publications["mavenJava"])
    }
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            // Publish the components generated by the 'java' plugin (JAR, POM)
            from(components["java"])

            pom {
                name.set("Higher-Kinded-J Annotations Processor")
                description.set("Bringing Higher-Kinded Types to Java Functional Patterns - Annotations Processor")
                url.set("https://github.com/higher-kinded-j/higher-kinded-j")

                licenses {
                    license {
                        name.set("The MIT License")
                        url.set("https://opensource.org/licenses/MIT")
                    }
                }
                developers {
                    developer {
                        id.set("higher-kinded-j")
                        name.set("Magnus Smith")
                        email.set("simulation-hkt@gmail.com")
                    }
                }
                scm {
                    connection.set("scm:git:git://github.com/higher-kinded-j/higher-kinded-j.git")
                    developerConnection.set("scm:git:ssh://github.com/higher-kinded-j/higher-kinded-j.git")
                    url.set("https://github.com/higher-kinded-j/higher-kinded-j")
                }
            }
        }
    }
    repositories {
        if (isSnapshotVersion) {
            maven {
                name = "CentralPortalSnapshots"
                url = uri("https://central.sonatype.com/repository/maven-snapshots/")
                credentials {
                    // These would be your Central Portal User Code and Passcode
                    username = System.getenv("CENTRAL_PORTAL_USERNAME")
                    password = System.getenv("CENTRAL_PORTAL_PASSWORD")
                }
            }
        }
    }
}
signing {
    // It still needs to be signed if it's part of a release
    isRequired = isReleaseBuild
    if (isReleaseBuild) {
        sign(publishing.publications["mavenJava"])
    }
}


if (!isSnapshotVersion) {
    centralPortal {
        username.set(System.getenv("CENTRAL_PORTAL_USERNAME"))
        password.set(System.getenv("CENTRAL_PORTAL_PASSWORD"))

        publishingType = net.thebugmc.gradle.sonatypepublisher.PublishingType.AUTOMATIC

        pom {
            name.set("Higher-Kinded-J Annotations Processor")
            description.set("Bringing Higher-Kinded Types to Java Functional Patterns - Annotations Processor")
            url.set("https://github.com/higher-kinded-j/higher-kinded-j")

            licenses {
                license {
                    name.set("The MIT License")
                    url.set("https://opensource.org/licenses/MIT")
                    distribution.set("repo")
                }
            }
            developers {
                developer {
                    id.set("higher-kinded-j")
                    name.set("Magnus Smith")
                    email.set("simulation-hkt@gmail.com")
                }
            }
            scm {
                connection.set("scm:git:git://github.com/higher-kinded-j/higher-kinded-j.git")
                developerConnection.set("scm:git:ssh://github.com/higher-kinded-j/higher-kinded-j.git")
                url.set("https://github.com/higher-kinded-j/higher-kinded-j")
            }
        }
    }
}