// Copyright (c) 2025 - 2026 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.example.basic.validated;

import org.higherkindedj.hkt.nonemptylist.NonEmptyList;
import org.higherkindedj.hkt.validated.FieldError;
import org.higherkindedj.hkt.validated.Validated;
import org.higherkindedj.optics.annotations.GenerateAssembly;

/**
 * Demonstrates {@code @GenerateAssembly} (issue #586): a per-record validated-assembly companion,
 * generated by the annotation processor, with one named method per component.
 *
 * <p>Compared with the hand-written {@code Validated.fields()} builder, the companion adds three
 * guarantees: labels come from the component names (no typos, rename-safe), field order cannot be
 * wrong (named, order-enforcing stage methods), and there is no arity ceiling (the generator emits
 * exact arity). The terminal {@code assemble()} invokes the canonical constructor.
 *
 * <p>Run with: {@code ./gradlew :hkj-examples:run
 * -PmainClass=org.higherkindedj.example.basic.validated.GeneratedAssemblyExample}
 */
public class GeneratedAssemblyExample {

  public static void main(String[] args) {
    System.out.println("=== @GenerateAssembly: per-record companions ===\n");

    labelledFromComponentNames();
    nestedCompanions();
  }

  private static void labelledFromComponentNames() {
    System.out.println("--- Labels come from the component names ---");

    Validated<NonEmptyList<FieldError>, SignupUser> good =
        SignupUserAssembly.fields()
            .name(Validated.validNel("Ada"))
            .email(Validated.validNel("ada@example.com"))
            .age(Validated.validNel(36))
            .assemble();
    System.out.println("good = " + good);
    // Valid(SignupUser[name=Ada, email=ada@example.com, age=36])

    Validated<NonEmptyList<FieldError>, SignupUser> bad =
        SignupUserAssembly.fields()
            .name(Validated.validNel("Ada"))
            .email(Validated.invalidNel(FieldError.of("not an email address")))
            .age(Validated.invalidNel(FieldError.of("not a number")))
            .assemble();
    System.out.println("bad  = " + bad);
    // Invalid(NonEmptyList[email: not an email address, age: not a number])
    System.out.println();
  }

  private static void nestedCompanions() {
    System.out.println("--- A sub-companion result feeds a component slot directly ---");

    Validated<NonEmptyList<FieldError>, PostalAddress> address =
        PostalAddressAssembly.fields()
            .street(Validated.validNel("Main St"))
            .zip(Validated.invalidNel(FieldError.of("not a postcode")))
            .assemble();

    Validated<NonEmptyList<FieldError>, AccountHolder> holder =
        AccountHolderAssembly.fields().name(Validated.validNel("Ada")).address(address).assemble();

    System.out.println("holder = " + holder);
    // Invalid(NonEmptyList[address.zip: not a postcode])
    System.out.println();
  }
}

@GenerateAssembly
record SignupUser(String name, String email, int age) {}

@GenerateAssembly
record PostalAddress(String street, String zip) {}

@GenerateAssembly
record AccountHolder(String name, PostalAddress address) {}
