// Fixture for .claude/skills/hkj-spring/SKILL.md
//
// Spring is on the gate's TEST classpath only (see hkj-examples/build.gradle.kts), so the skill's
// controller, error-mapping, client and effect-boundary snippets are compiled against the real
// starter rather than left unchecked. Without those dependencies the gate could not compile Spring
// code at all, and this skill is the one most likely to be read by an assistant writing a controller.
//
// Two things here are deliberately REAL rather than stubbed:
//
//  * `UserClientApi` is a real @HkjHttpClient interface, so the client processor generates
//    UserClientApiHttpExchange / UserClientApiClient / UserClientApiClientConfiguration for it. The
//    skill's client snippets are checked against genuinely generated code, not a stand-in. A snippet
//    that declares its own UserClientApi shadows this one, and the processor generates from that.
//  * OrderOp / InventoryOp / NotifyOp are real @EffectAlgebra sources, so `OrderOpInterpreter` and
//    friends are generated by the real processor. The EffectBoundary snippets extend the generated
//    interpreter and name the generated witnesses.
//
// Java has no type alias, so the witness of a three-algebra composition is spelled out wherever it
// appears (`Interpreters.combine` nests EitherF to the right). The skill says so, and spells it too.
//
// NOTE: the imports below look unused *here*. They are for the snippet this file is spliced into.
// That is why spotless excludes src/test/resources/fixtures.

import static org.assertj.core.api.Assertions.assertThat;

import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import org.higherkindedj.hkt.Kind;
import org.higherkindedj.hkt.Unit;
import org.higherkindedj.hkt.effect.CompletableFuturePath;
import org.higherkindedj.hkt.effect.EitherOrBothPath;
import org.higherkindedj.hkt.effect.EitherPath;
import org.higherkindedj.hkt.effect.FreePath;
import org.higherkindedj.hkt.effect.IOPath;
import org.higherkindedj.hkt.effect.Path;
import org.higherkindedj.hkt.effect.VStreamPath;
import org.higherkindedj.hkt.effect.VTaskPath;
import org.higherkindedj.hkt.effect.annotation.EffectAlgebra;
import org.higherkindedj.hkt.effect.boundary.EffectBoundary;
import org.higherkindedj.hkt.either.Either;
import org.higherkindedj.hkt.eitherf.EitherFKind;
import org.higherkindedj.hkt.eitherf.Interpreters;
import org.higherkindedj.hkt.free.Free;
import org.higherkindedj.hkt.io.IO;
import org.higherkindedj.hkt.io.IOKind;
import org.higherkindedj.hkt.nonemptylist.NonEmptyList;
import org.higherkindedj.hkt.resilience.CircuitBreaker;
import org.higherkindedj.hkt.resilience.RetryPolicy;
import org.higherkindedj.hkt.validated.Validated;
import org.higherkindedj.spring.autoconfigure.effect.EnableEffectBoundary;
import org.higherkindedj.spring.autoconfigure.effect.Interpreter;
import org.higherkindedj.spring.autoconfigure.test.EffectTest;
import org.higherkindedj.spring.client.HkjHttpClient;
import org.higherkindedj.spring.web.returnvalue.ErrorStatusCodeMapper;
import org.higherkindedj.spring.web.returnvalue.ErrorStatusCodeStrategy;
import org.higherkindedj.spring.web.returnvalue.HttpHeaderCarrier;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.service.annotation.GetExchange;
import org.springframework.web.service.annotation.HttpExchange;
import org.springframework.web.service.annotation.PostExchange;

// ---------------------------------------------------------------------------------------------
// The reader's own domain, which the skill quite properly elides.
// ---------------------------------------------------------------------------------------------

record User(String id, String name) {}

record UserDto(String id, String name) {}

record UserRequest(String name, String email) {}

record ValidationError(String field, String message) {}

record Report(String id, String body) {}

/** The reader's own SSE payload. NOT `org.higherkindedj.hkt.Update`, which is a different type. */
record Update(String id, String text) {}

record OrderRequest(String sku, int quantity) {}

enum OrderStatus {
  PENDING,
  CONFIRMED
}

record OrderResult(String orderId, OrderStatus status) {
  OrderResult(String orderId) {
    this(orderId, OrderStatus.PENDING);
  }
}

record Order(String sku, int quantity) {}

record Payment(String id) {}

sealed interface DomainError {
  record NotFound(String what, String id) implements DomainError {}

  record Validation(String message) implements DomainError {}

  record PaymentFailed(String reason) implements DomainError {}
}

/** Carries a field the status strategy switches on; a snippet declares its own richer version. */
record MfaThrottledError(int retryAfter) implements DomainError {}

sealed interface ApiError {
  record NotFound(String what) implements ApiError {}

  record Unavailable(String what) implements ApiError {}

  record RateLimited(Duration retryAfter) implements ApiError {}
}

// ---------------------------------------------------------------------------------------------
// The reader's own services and repositories.
// ---------------------------------------------------------------------------------------------

interface UserService {
  Either<DomainError, User> findById(String id);

  /**
   * Generic in the error element on purpose: the page shows this service accumulating into {@code
   * List<ValidationError>} in one snippet and into {@code List<String>} in another, and a fixture
   * may not contradict either.
   */
  <E> Validated<List<E>, User> validateAndCreate(UserRequest request);
}

interface ReportService {
  EitherOrBothPath<NonEmptyList<String>, Report> buildReport(String id);
}

interface ReportCache {
  boolean isStale();
}

interface ReportRenderer {
  Report render(String id);
}

interface UpdateService {
  VStreamPath<Update> updates();
}

interface OrderRepository {
  OrderResult save(OrderRequest request);
}

/** The client the page declares. A snippet that declares its own shadows this one. */
@HttpExchange("/users")
@HkjHttpClient
interface UserClientApi {

  @GetExchange("/{id}")
  EitherPath<ApiError, UserDto> getUser(@PathVariable String id);

  @PostExchange
  VTaskPath<Either<ApiError, UserDto>> create(@RequestBody UserDto body);
}

// ---------------------------------------------------------------------------------------------
// The reader's own effect algebras, which the EffectBoundary snippets assume.
// ---------------------------------------------------------------------------------------------

@EffectAlgebra
sealed interface OrderOp<A> permits OrderOp.CreateOrder {

  <B> OrderOp<B> mapK(Function<? super A, ? extends B> f);

  record CreateOrder<A>(OrderRequest request, Function<OrderResult, A> k) implements OrderOp<A> {
    @Override
    public <B> OrderOp<B> mapK(Function<? super A, ? extends B> f) {
      return new CreateOrder<>(request, k.andThen(f));
    }
  }
}

@EffectAlgebra
sealed interface InventoryOp<A> permits InventoryOp.Reserve {

  <B> InventoryOp<B> mapK(Function<? super A, ? extends B> f);

  record Reserve<A>(String sku, int quantity, Function<Boolean, A> k) implements InventoryOp<A> {
    @Override
    public <B> InventoryOp<B> mapK(Function<? super A, ? extends B> f) {
      return new Reserve<>(sku, quantity, k.andThen(f));
    }
  }
}

@EffectAlgebra
sealed interface NotifyOp<A> permits NotifyOp.Notify {

  <B> NotifyOp<B> mapK(Function<? super A, ? extends B> f);

  record Notify<A>(String message, Function<Unit, A> k) implements NotifyOp<A> {
    @Override
    public <B> NotifyOp<B> mapK(Function<? super A, ? extends B> f) {
      return new Notify<>(message, k.andThen(f));
    }
  }
}

/** The reader's production interpreters, extending the generated skeletons. */
final class ProductionOrderInterpreter extends OrderOpInterpreter<IOKind.Witness> {
  @Override
  protected <A> Kind<IOKind.Witness, A> handleCreateOrder(OrderOp.CreateOrder<A> op) {
    return IO.delay(() -> op.k().apply(new OrderResult("ORD-1", OrderStatus.CONFIRMED)));
  }
}

final class ProductionInventoryInterpreter extends InventoryOpInterpreter<IOKind.Witness> {
  @Override
  protected <A> Kind<IOKind.Witness, A> handleReserve(InventoryOp.Reserve<A> op) {
    return IO.delay(() -> op.k().apply(Boolean.TRUE));
  }
}

final class ProductionNotificationInterpreter extends NotifyOpInterpreter<IOKind.Witness> {
  @Override
  protected <A> Kind<IOKind.Witness, A> handleNotify(NotifyOp.Notify<A> op) {
    return IO.delay(() -> op.k().apply(Unit.INSTANCE));
  }
}

/**
 * The reader's order service. Its programs are written against the composed witness: Java has no
 * type alias, so the {@code EitherF} nesting that {@code Interpreters.combine} produces is spelled
 * out, exactly as the skill spells it.
 */
interface OrderService {
  Free<
          EitherFKind.Witness<
              OrderOpKind.Witness,
              EitherFKind.Witness<InventoryOpKind.Witness, NotifyOpKind.Witness>>,
          OrderResult>
      processOrder(OrderRequest request);

  /** One algebra, so one witness: what the FreePath controller snippet returns. */
  FreePath<OrderOpKind.Witness, OrderStatus> getOrderStatus(String id);
}

class Fixture {

  static final UserService userService = null;
  static final ReportService reportService = null;
  static final ReportCache cache = null;
  static final ReportRenderer renderer = null;
  static final UpdateService updateService = null;
  static final OrderService orderService = null;
  static final UserClientApi userClientApi = null;

  static final UserDto body = new UserDto("42", "Ada");
  static final CircuitBreaker breaker = CircuitBreaker.withDefaults();

  /** The boundary the controller snippets inject: a real three-algebra composition. */
  static final EffectBoundary<
          EitherFKind.Witness<
              OrderOpKind.Witness,
              EitherFKind.Witness<InventoryOpKind.Witness, NotifyOpKind.Witness>>>
      boundary =
          EffectBoundary.of(
              Interpreters.combine(
                  new ProductionOrderInterpreter(),
                  new ProductionInventoryInterpreter(),
                  new ProductionNotificationInterpreter()));

  /**
   * Deliberately does NOT name a DomainError variant: the "Designing Error Class Names" snippet
   * declares its own DomainError, which shadows the one above, and a fixture that reached into the
   * shadowed type would stop that snippet compiling.
   */
  static EitherPath<DomainError, User> findUser(String id) {
    return Path.left(null);
  }

  static EitherPath<String, Order> validateOrder(OrderRequest request) {
    return Path.right(new Order(request.sku(), request.quantity()));
  }

  static EitherPath<String, Payment> chargePayment(User user, Order order) {
    return Path.right(new Payment("pay-1"));
  }
}
