plugins {
  `maven-publish`
    signing
  id("net.thebugmc.gradle.sonatype-central-portal-publisher") version "1.2.4"
    jacoco
}

dependencies {


//  // API dependencies
  api("org.jspecify:jspecify:1.0.0")

  // Testing dependencies
  testImplementation(platform("org.junit:junit-bom:5.13.0"))
  testImplementation("org.junit.jupiter:junit-jupiter")
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")
  testImplementation("org.assertj:assertj-core:3.27.3")
}


tasks.jacocoTestReport {
  dependsOn(tasks.test)
  reports {
    xml.required.set(true)
    html.required.set(true)
  }
  // Jacoco configuration remains specific to this module's source code
}

tasks.javadoc {
  source = sourceSets.main.get().allJava
  exclude("org/higherkindedj/example/**")
  (options as? CoreJavadocOptions)?.addStringOption("Xdoclint:none", "-quiet")
}
tasks.test {
  useJUnitPlatform()
  finalizedBy(tasks.jacocoTestReport)
  jvmArgs = listOf("--add-opens", "org.higherkindedj.hkj/org.higherkindedj.internal=ALL-UNNAMED")
}

tasks.jacocoTestReport {
  dependsOn(tasks.test)

  reports {
    xml.required.set(true)
    html.required.set(true)
    csv.required.set(false)
  }

  val mainSourceSet = sourceSets.main.get()
  val compiledClasses = mainSourceSet.output.classesDirs
  classDirectories.setFrom(
      files(
          compiledClasses.map { dir ->
            fileTree(dir).apply {
              exclude(
                  "**/example/**", // Exclude the example package
                  "**/*Kind.class",
                  "**/*Holder*.class"
                  )
            }
          }))
  sourceDirectories.setFrom(files(mainSourceSet.allSource.srcDirs))
}

val isSnapshotVersion: Boolean by rootProject.extra
val isReleaseBuild: Boolean by rootProject.extra

signing {
  isRequired = isReleaseBuild
  if (isReleaseBuild) {
    sign(publishing.publications["mavenJava"])
  }
}

publishing {
  publications {
    create<MavenPublication>("mavenJava") {
      // Publish the components generated by the 'java' plugin (JAR, POM)
      from(components["java"])

      pom {
        name.set("Higher-Kinded-J Core Library")
        description.set("Bringing Higher-Kinded Types to Java Functional Patterns - Core Library")
        url.set("https://github.com/higher-kinded-j/higher-kinded-j")

        licenses {
          license {
            name.set("The MIT License")
            url.set("https://opensource.org/licenses/MIT")
          }
        }
        developers {
          developer {
            id.set("higher-kinded-j")
            name.set("Magnus Smith")
            email.set("simulation-hkt@gmail.com")
          }
        }
        scm {
          connection.set("scm:git:git://github.com/higher-kinded-j/higher-kinded-j.git")
          developerConnection.set("scm:git:ssh://github.com/higher-kinded-j/higher-kinded-j.git")
          url.set("https://github.com/higher-kinded-j/higher-kinded-j")
        }
      }
    }
  }
  repositories {
    if (isSnapshotVersion) {
      maven {
        name = "CentralPortalSnapshots"
        url = uri("https://central.sonatype.com/repository/maven-snapshots/")
        credentials {
          // These would be your Central Portal User Code and Passcode
          username = System.getenv("CENTRAL_PORTAL_USERNAME")
          password = System.getenv("CENTRAL_PORTAL_PASSWORD")
        }
      }
    }
  }
}
signing {
  // It still needs to be signed if it's part of a release
  isRequired = isReleaseBuild
  if (isReleaseBuild) {
    sign(publishing.publications["mavenJava"])
  }
}


if (!isSnapshotVersion) {
  centralPortal {
    username.set(System.getenv("CENTRAL_PORTAL_USERNAME"))
    password.set(System.getenv("CENTRAL_PORTAL_PASSWORD"))

    publishingType = net.thebugmc.gradle.sonatypepublisher.PublishingType.AUTOMATIC

    pom {
      name.set("Higher-Kinded-J Core Library")
      description.set("Bringing Higher-Kinded Types to Java Functional Patterns - Core Library")
      url.set("https://github.com/higher-kinded-j/higher-kinded-j")

      licenses {
        license {
          name.set("The MIT License")
          url.set("https://opensource.org/licenses/MIT")
          distribution.set("repo")
        }
      }
      developers {
        developer {
          id.set("higher-kinded-j")
          name.set("Magnus Smith")
          email.set("simulation-hkt@gmail.com")
        }
      }
      scm {
        connection.set("scm:git:git://github.com/higher-kinded-j/higher-kinded-j.git")
        developerConnection.set("scm:git:ssh://github.com/higher-kinded-j/higher-kinded-j.git")
        url.set("https://github.com/higher-kinded-j/higher-kinded-j")
      }
    }
  }
}



