// Copyright (c) 2025 - 2026 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.hkt.error;

import static org.higherkindedj.hkt.util.validation.Operation.CONSTRUCTION;

import org.higherkindedj.hkt.util.validation.Validation;
import org.jspecify.annotations.NullMarked;

/**
 * Effect algebra for raising typed business errors within Free monad programs.
 *
 * <p>{@code ErrorOp<E, A>} has two type parameters: {@code E} is the error type (fixed by the user,
 * e.g. {@code BusinessError}), and {@code A} is the HKT-varying parameter. This is hand-written
 * rather than generated by {@code @EffectAlgebra} because the processor expects a single type
 * parameter {@code <A>}.
 *
 * <h2>Usage</h2>
 *
 * <p>Include {@code ErrorOp} in a composed effect set to enable typed error raising:
 *
 * <pre>{@code
 * // Raise a business error
 * ErrorOps.raise(new InsufficientFundsError(amount));
 * }</pre>
 *
 * <p>Error recovery is handled separately via {@code Free.HandleError}, not through ErrorOp itself.
 *
 * @param <E> The error type (fixed for a given program)
 * @param <A> The result type (HKT-varying parameter)
 * @see ErrorOpKind
 * @see org.higherkindedj.hkt.free.Free.HandleError
 */
@NullMarked
public sealed interface ErrorOp<E, A> permits ErrorOp.Raise {

  /**
   * Raises an error of type E. This operation never produces a value of type A; it always
   * short-circuits the program.
   *
   * @param error The error to raise
   * @param <E> The error type
   * @param <A> The phantom result type
   */
  record Raise<E, A>(E error) implements ErrorOp<E, A> {
    public Raise {
      Validation.function().require(error, "error", CONSTRUCTION);
    }
  }
}
