// Copyright (c) 2025 - 2026 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.example.book.effect.pathsource;

import static org.higherkindedj.example.book.effect.pathsource.OutcomeKindHelper.OUTCOME;
import static org.higherkindedj.example.book.effect.pathsource.TracedKindHelper.TRACED;

import org.higherkindedj.hkt.effect.GenericPath;
import org.higherkindedj.hkt.effect.Path;

/**
 * The code shown on the book's <a
 * href="https://higher-kinded-j.github.io/effect/path_source.html">Custom Paths with
 * {@code @PathSource}</a> page. The page {@code {{#include}}}s the anchored regions, so it cannot
 * drift from the API. {@code BookExampleOutputTest} runs {@code main} and holds each output comment
 * to what it prints, and {@code PathSourceBookTest} covers what the page says without printing it.
 *
 * <p>{@code TracedPath} and {@code OutcomePath} are generated by the annotation processor from the
 * {@code @PathSource} on {@link Traced} and on {@link Outcome}.
 */
public final class PathSourceBook {

  private PathSourceBook() {}

  public static void main(String[] args) {
    // ANCHOR: first_path
    TracedPath<Integer> priced =
        TracedPath.of(Traced.of(1200, "priced the basket"), TracedMonad.INSTANCE);

    TracedPath<Integer> total =
        priced
            .map(pence -> pence * 6 / 5) // adds 20% VAT
            .via(
                pence ->
                    TracedPath.of(
                        Traced.of(pence - 200, "applied a voucher"), TracedMonad.INSTANCE));

    Traced<Integer> result = TRACED.narrow(total.run());
    // Traced[value=1240, log=[priced the basket, applied a voucher]]
    // ANCHOR_END: first_path
    System.out.println(result);

    // ANCHOR: object_methods
    String shown = priced.toString();
    // TracedPath(Traced[value=1200, log=[priced the basket]])
    boolean same =
        priced.equals(TracedPath.of(Traced.of(1200, "priced the basket"), TracedMonad.INSTANCE));
    // true
    // ANCHOR_END: object_methods
    System.out.println(shown);
    System.out.println(same);

    // ANCHOR: zip_with
    TracedPath<Integer> delivery =
        TracedPath.of(Traced.of(350, "quoted delivery"), TracedMonad.INSTANCE);

    Traced<Integer> withDelivery = TRACED.narrow(priced.zipWith(delivery, Integer::sum).run());
    // Traced[value=1550, log=[priced the basket, quoted delivery]]
    // ANCHOR_END: zip_with
    System.out.println(withDelivery);

    // ANCHOR: recover
    OutcomePath<String> reservation =
        OutcomePath.of(reserve("SKU-42"), OutcomeMonad.INSTANCE, OutcomeMonad.INSTANCE);

    Outcome<String> backOrdered =
        OUTCOME.narrow(reservation.recover(problem -> "back-ordered: " + problem.reason()).run());
    // Ok[value=back-ordered: SKU-42 is out of stock]

    Outcome<String> relabelled =
        OUTCOME.narrow(
            reservation.mapError(problem -> new Problem("checkout: " + problem.reason())).run());
    // Failed[problem=Problem[reason=checkout: SKU-42 is out of stock]]
    // ANCHOR_END: recover
    System.out.println(backOrdered);
    System.out.println(relabelled);
  }

  /**
   * The same recovery through {@code GenericPath}, whose {@code recover} takes the error type the
   * caller names: this caller names the wrong one, so it compiles and fails when the error reaches
   * it. Not called from {@code main}; the test asserts the failure.
   */
  static GenericPath<OutcomeKind.Witness, String> genericRecover() {
    // ANCHOR: generic_recover
    GenericPath<OutcomeKind.Witness, String> reservation =
        GenericPath.of(reserve("SKU-42"), OutcomeMonad.INSTANCE);

    // compiles, and throws ClassCastException: the error is a Problem
    GenericPath<OutcomeKind.Witness, String> backOrdered =
        reservation.<String>recover(reason -> "back-ordered: " + reason.strip());
    // ANCHOR_END: generic_recover
    return backOrdered;
  }

  /**
   * A generated Path back in {@code GenericPath}, for an API that takes one, such as {@code
   * ForPath}: the Path's {@code Kind} with the same {@code Monad}.
   */
  static GenericPath<TracedKind.Witness, Integer> toGeneric(TracedPath<Integer> priced) {
    // ANCHOR: to_generic
    GenericPath<TracedKind.Witness, Integer> generic =
        Path.generic(priced.run(), TracedMonad.INSTANCE);
    // ANCHOR_END: to_generic
    return generic;
  }

  /** Reserves stock for a product: {@code SKU-42} has none left. */
  public static Outcome<String> reserve(String sku) {
    return sku.equals("SKU-42")
        ? new Outcome.Failed<>(new Problem(sku + " is out of stock"))
        : new Outcome.Ok<>("reserved " + sku);
  }
}
