// Copyright (c) 2025 - 2026 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.optics.processing;

import java.io.IOException;
import java.io.Writer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;

/**
 * Generates {@code CoupledLenses}, a utility class holding {@code coupled3} ... {@code coupledN}
 * static factories that build a {@code Lens<S, TupleN<...>>} focusing on a coupled group of fields,
 * reconstructed atomically.
 *
 * <p>The binary form is the hand-written {@code Lens.paired}; this generator emits the N-ary ladder
 * beyond it. Two overloads per arity, mirroring {@code Lens.paired}:
 *
 * <ul>
 *   <li>a preserving form that takes {@code (S, A, B, C, ...) -> S} so other fields of the source
 *       are kept;
 *   <li>a simple form that takes {@code (A, B, C, ...) -> S} for when the focused fields fully
 *       determine the source.
 * </ul>
 *
 * <p>The output file is one class with many static methods, distinct from {@code TupleGenerator}'s
 * one-file-per-arity shape.
 */
final class CoupledLensGenerator {

  private static final String PACKAGE = "org.higherkindedj.optics.util";
  private static final String CLASS_NAME = "CoupledLenses";

  private static final String[] TYPE_PARAMS = {"A", "B", "C", "D", "E", "F", "G", "H", "I"};

  private static final String[] ORDINAL_LOWER = {
    "first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth", "ninth"
  };

  /**
   * Cross-field invariants past 5 are rare and past 9 vanishing; the ladder caps at the smaller of
   * the two name arrays so raising one without the other can never push past the safe range. To
   * grow the ladder, append entries to both arrays (the cap moves up automatically).
   */
  static final int MAX_SUPPORTED_ARITY = Math.min(TYPE_PARAMS.length, ORDINAL_LOWER.length);

  /** Binary arity is covered by {@code Lens.paired}; the ladder starts at 3. */
  static final int MIN_SUPPORTED_ARITY = 3;

  private CoupledLensGenerator() {}

  static void generate(
      int minArity, int maxArity, ProcessingEnvironment processingEnv, Element originatingElement)
      throws IOException {
    int effectiveMin = Math.max(minArity, MIN_SUPPORTED_ARITY);
    int effectiveMax = Math.min(maxArity, MAX_SUPPORTED_ARITY);
    if (effectiveMin > effectiveMax) {
      return;
    }

    StringBuilder sb = new StringBuilder();
    sb.append("// Generated by hkj-processor. Do not edit.\n");
    sb.append("package ").append(PACKAGE).append(";\n\n");

    // Imports: every Function arity from the simple form (N) up to the preserving form (N+1).
    // Starting at effectiveMin avoids unused-import warnings when the request narrows the range.
    for (int i = effectiveMin; i <= effectiveMax + 1; i++) {
      sb.append("import org.higherkindedj.hkt.function.Function").append(i).append(";\n");
    }
    for (int i = effectiveMin; i <= effectiveMax; i++) {
      sb.append("import org.higherkindedj.hkt.tuple.Tuple").append(i).append(";\n");
    }
    sb.append("import org.higherkindedj.optics.Lens;\n");
    sb.append("import org.higherkindedj.optics.annotations.Generated;\n\n");

    sb.append("/**\n");
    sb.append(" * N-ary coupled-group lenses, the arity ladder above {@link Lens#paired}.\n");
    sb.append(" *\n");
    sb.append(
        " * <p>Each {@code coupledN} factory builds a {@code Lens<S, TupleN<...>>} that reads the\n");
    sb.append(
        " * focused fields together and reconstructs the source <em>atomically</em> from a new\n");
    sb.append(
        " * tuple, so a record constructor that enforces a cross-field invariant ({@code lo <= hi},\n");
    sb.append(
        " * a currency-precision pair, a non-empty/min/max triple) never sees an intermediate state\n");
    sb.append(" * that violates it.\n");
    sb.append(" *\n");
    sb.append(
        " * <p>Two overloads per arity, mirroring {@link Lens#paired}: a preserving form taking\n");
    sb.append(
        " * {@code (S, A, B, ...) -> S} (keeps other fields), and a simple form taking {@code\n");
    sb.append(" * (A, B, ...) -> S} for when the focused fields fully determine the source.\n");
    sb.append(" */\n");
    sb.append("@Generated\n");
    sb.append("public final class ").append(CLASS_NAME).append(" {\n\n");
    sb.append("  private ").append(CLASS_NAME).append("() {}\n\n");

    for (int n = effectiveMin; n <= effectiveMax; n++) {
      generatePreservingForm(sb, n);
      generateSimpleForm(sb, n);
    }

    sb.append("}\n");

    try (Writer writer =
        processingEnv
            .getFiler()
            .createSourceFile(PACKAGE + "." + CLASS_NAME, originatingElement)
            .openWriter()) {
      writer.write(sb.toString());
    }
  }

  private static void generatePreservingForm(StringBuilder sb, int n) {
    String tuple = "Tuple" + n;
    String fn = "Function" + (n + 1);
    String typeParams = typeParamsList(n);

    sb.append("  /**\n");
    sb.append("   * Combines ")
        .append(n)
        .append(" lenses into one {@code Lens<S, ")
        .append(tuple)
        .append("<")
        .append(typeParams)
        .append(">>} reconstructed atomically.\n");
    sb.append("   *\n");
    sb.append(
        "   * <p>The {@code reconstructor} receives the original source (for accessing fields\n");
    sb.append("   * outside the coupled group) plus all ").append(n).append(" new values.\n");
    sb.append("   */\n");
    sb.append("  public static <S, ").append(typeParams).append("> Lens<S, ").append(tuple);
    sb.append("<").append(typeParams).append(">> coupled").append(n).append("(\n");
    for (int i = 0; i < n; i++) {
      sb.append("      Lens<S, ").append(TYPE_PARAMS[i]).append("> ").append(ORDINAL_LOWER[i]);
      sb.append(",\n");
    }
    sb.append("      ")
        .append(fn)
        .append("<S, ")
        .append(typeParams)
        .append(", S> reconstructor) {\n");

    sb.append("    return Lens.of(\n");
    sb.append("        s -> new ").append(tuple).append("<>(");
    for (int i = 0; i < n; i++) {
      if (i > 0) sb.append(", ");
      sb.append(ORDINAL_LOWER[i]).append(".get(s)");
    }
    sb.append("),\n");
    sb.append("        (s, tuple) -> reconstructor.apply(s");
    for (int i = 0; i < n; i++) {
      sb.append(", tuple._").append(i + 1).append("()");
    }
    sb.append("));\n");
    sb.append("  }\n\n");
  }

  private static void generateSimpleForm(StringBuilder sb, int n) {
    String tuple = "Tuple" + n;
    String fn = "Function" + n;
    String typeParams = typeParamsList(n);

    sb.append("  /**\n");
    sb.append("   * Convenience overload: like {@link #coupled").append(n).append("(");
    for (int i = 0; i < n; i++) {
      if (i > 0) sb.append(", ");
      sb.append("Lens");
    }
    sb.append(", Function").append(n + 1).append(")} but takes a constructor that ignores the\n");
    sb.append("   * source. Use when the ")
        .append(n)
        .append(" focused fields fully determine {@code S}.\n");
    sb.append("   */\n");
    sb.append("  public static <S, ").append(typeParams).append("> Lens<S, ").append(tuple);
    sb.append("<").append(typeParams).append(">> coupled").append(n).append("(\n");
    for (int i = 0; i < n; i++) {
      sb.append("      Lens<S, ").append(TYPE_PARAMS[i]).append("> ").append(ORDINAL_LOWER[i]);
      sb.append(",\n");
    }
    sb.append("      ").append(fn).append("<").append(typeParams).append(", S> constructor) {\n");

    sb.append("    return coupled").append(n).append("(");
    for (int i = 0; i < n; i++) {
      sb.append(ORDINAL_LOWER[i]).append(", ");
    }
    sb.append("(s");
    for (int i = 0; i < n; i++) {
      sb.append(", ").append(ORDINAL_LOWER[i]).append("Value");
    }
    sb.append(") -> constructor.apply(");
    for (int i = 0; i < n; i++) {
      if (i > 0) sb.append(", ");
      sb.append(ORDINAL_LOWER[i]).append("Value");
    }
    sb.append("));\n");
    sb.append("  }\n\n");
  }

  private static String typeParamsList(int n) {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < n; i++) {
      if (i > 0) sb.append(", ");
      sb.append(TYPE_PARAMS[i]);
    }
    return sb.toString();
  }
}
