// Copyright (c) 2025 - 2026 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.optics.processing;

import com.google.auto.service.AutoService;
import com.palantir.javapoet.*;
import java.io.IOException;
import java.util.List;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.RecordComponentElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.TypeParameterElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import javax.tools.Diagnostic;
import org.higherkindedj.optics.Fold;
import org.higherkindedj.optics.annotations.GenerateFolds;
import org.higherkindedj.optics.processing.util.ExcludeFromJacocoGeneratedReport;
import org.higherkindedj.optics.processing.util.NestedOptic;
import org.higherkindedj.optics.processing.util.NestedTypeNames;
import org.higherkindedj.optics.processing.util.ProcessorUtils;

/** Annotation processor that generates Fold optics for record types. */
@AutoService(Processor.class)
@SupportedAnnotationTypes("org.higherkindedj.optics.annotations.GenerateFolds")
public class FoldProcessor extends AbstractProcessor {

  private static final ClassName GENERATED =
      ClassName.get("org.higherkindedj.optics.annotations", "Generated");
  private static final ClassName MONOID = ClassName.get("org.higherkindedj.hkt", "Monoid");
  private static final ClassName FUNCTION = ClassName.get("java.util.function", "Function");

  @Override
  public SourceVersion getSupportedSourceVersion() {
    return SourceVersion.latestSupported();
  }

  /** Creates a new FoldProcessor. */
  public FoldProcessor() {}

  @Override
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
    for (TypeElement annotation : annotations) {
      Set<? extends Element> annotatedElements = roundEnv.getElementsAnnotatedWith(annotation);
      for (Element element : annotatedElements) {
        if (element.getKind() != ElementKind.RECORD) {
          error("The @GenerateFolds annotation can only be applied to records.", element);
          continue;
        }
        writeFoldsFile((TypeElement) element);
      }
    }
    return true;
  }

  @ExcludeFromJacocoGeneratedReport
  private void writeFoldsFile(TypeElement element) {
    try {
      generateFoldsFile(element);
    } catch (IOException e) {
      error("Could not generate folds file: " + e.getMessage(), element);
    }
  }

  private void generateFoldsFile(TypeElement recordElement) throws IOException {
    String recordName = recordElement.getSimpleName().toString();
    String defaultPackage =
        processingEnv.getElementUtils().getPackageOf(recordElement).getQualifiedName().toString();

    // Check for custom target package in annotation
    GenerateFolds annotation = recordElement.getAnnotation(GenerateFolds.class);
    String targetPackage = annotation.targetPackage();
    String packageName = targetPackage.isEmpty() ? defaultPackage : targetPackage;

    String foldsClassName = recordName + "Folds";

    TypeSpec.Builder foldsClassBuilder =
        TypeSpec.classBuilder(foldsClassName)
            .addOriginatingElement(recordElement)
            .addAnnotation(GENERATED)
            .addJavadoc(
                "Generated optics for {@link $T}. Do not edit.", ClassName.get(recordElement))
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build());

    List<? extends RecordComponentElement> components = recordElement.getRecordComponents();
    TypeName recordTypeName = getParameterizedTypeName(recordElement);

    final NestedTypeNames names = new NestedTypeNames(foldsClassName);
    for (RecordComponentElement component : components) {
      createFold(component, recordElement, recordTypeName, names).addTo(foldsClassBuilder);
    }

    JavaFile javaFile =
        JavaFile.builder(packageName, foldsClassBuilder.build())
            .addFileComment("Generated by hkj-optics-processor. Do not edit.")
            .build();

    javaFile.writeTo(processingEnv.getFiler());
  }

  private TypeName getParameterizedTypeName(TypeElement typeElement) {
    List<? extends TypeParameterElement> typeParameters = typeElement.getTypeParameters();
    if (typeParameters.isEmpty()) {
      return ClassName.get(typeElement);
    } else {
      List<TypeVariableName> typeVars =
          typeParameters.stream().map(ProcessorUtils::typeVariableOf).toList();
      return ParameterizedTypeName.get(
          ClassName.get(typeElement), typeVars.toArray(new TypeName[0]));
    }
  }

  private NestedOptic createFold(
      RecordComponentElement component,
      TypeElement recordElement,
      TypeName recordTypeName,
      NestedTypeNames names) {

    String componentName = component.getSimpleName().toString();
    TypeName componentTypeName = ProcessorUtils.typeNameOf(component.asType());

    // Check if this is an Iterable type (List, Set, etc.)
    boolean isIterable = isIterableType(component.asType());
    TypeName targetType = isIterable ? getElementType(component) : componentTypeName.box();

    ParameterizedTypeName foldTypeName =
        ParameterizedTypeName.get(ClassName.get(Fold.class), recordTypeName, targetType);

    // The monoid's type variable is declared beside the record's own, so it takes a name the
    // record has not.
    TypeVariableName monoidType =
        TypeVariableName.get(ProcessorUtils.freeTypeVariableName("M", recordElement));
    MethodSpec.Builder foldMap =
        MethodSpec.methodBuilder("foldMap")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .addTypeVariable(monoidType)
            .returns(monoidType)
            .addParameter(ParameterizedTypeName.get(MONOID, monoidType), "monoid")
            .addParameter(
                ParameterizedTypeName.get(
                    FUNCTION,
                    WildcardTypeName.supertypeOf(targetType),
                    WildcardTypeName.subtypeOf(monoidType)),
                "f")
            .addParameter(recordTypeName, "source");
    if (isIterable) {
      // For Iterable types, fold over each element
      foldMap
          .addStatement("$T result = monoid.empty()", monoidType)
          .beginControlFlow("for (var element : source.$L())", componentName)
          .addStatement("result = monoid.combine(result, f.apply(element))")
          .endControlFlow()
          .addStatement("return result");
    } else {
      // For non-Iterable types, just apply function to the single value
      foldMap.addStatement("return f.apply(source.$L())", componentName);
    }

    String implementationName = names.claim(componentName, "Fold");
    TypeSpec.Builder implementation =
        TypeSpec.classBuilder(implementationName)
            .addAnnotation(GENERATED)
            .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .addSuperinterface(foldTypeName)
            .addMethod(foldMap.build());

    MethodSpec.Builder factory =
        MethodSpec.methodBuilder(componentName)
            .addJavadoc(
                "Creates a {@link $T} for the {@code $L} field of a {@link $T}.\n\n"
                    + "@return A non-null {@code Fold<$T, $T>}.",
                Fold.class,
                component.getSimpleName(),
                recordTypeName,
                recordTypeName,
                targetType)
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .returns(foldTypeName);

    // The implementation is declared beside the factory, not inside it, so it declares the
    // record's type variables for itself.
    for (TypeParameterElement typeParameter : recordElement.getTypeParameters()) {
      TypeVariableName typeVariable = ProcessorUtils.typeVariableOf(typeParameter);
      factory.addTypeVariable(typeVariable);
      implementation.addTypeVariable(typeVariable);
    }
    String typeArguments = recordElement.getTypeParameters().isEmpty() ? "" : "<>";

    return new NestedOptic(
        implementation.build(),
        factory.addStatement("return new $L$L()", implementationName, typeArguments).build());
  }

  private boolean isIterableType(TypeMirror type) {
    if (!(type instanceof DeclaredType)) {
      return false;
    }
    Types typeUtils = processingEnv.getTypeUtils();
    Elements elementUtils = processingEnv.getElementUtils();

    // Get the Iterable type element
    TypeElement iterableElement = elementUtils.getTypeElement("java.lang.Iterable");
    if (iterableElement == null) {
      return false;
    }

    // Erase both types to compare raw types (handles generic parameters)
    TypeMirror erasedType = typeUtils.erasure(type);
    TypeMirror erasedIterable = typeUtils.erasure(iterableElement.asType());

    // Check if the type is a subtype of Iterable
    return typeUtils.isSubtype(erasedType, erasedIterable);
  }

  private TypeName getElementType(RecordComponentElement component) {
    // Only called for iterable components, and isIterableType requires a declared type. A wildcard
    // element is named as the type it stands for, since a wildcard cannot be written into the
    // fold's signature.
    DeclaredType containerType = (DeclaredType) component.asType();
    if (!containerType.getTypeArguments().isEmpty()) {
      return ProcessorUtils.resolvedTypeNameOf(containerType.getTypeArguments().getFirst()).box();
    }
    return ClassName.get(Object.class);
  }

  private void error(String msg, Element e) {
    processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, msg, e);
  }
}
