// Copyright (c) 2025 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.optics.processing;

import com.google.auto.service.AutoService;
import com.palantir.javapoet.*;
import java.io.IOException;
import java.util.List;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;
import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import org.higherkindedj.hkt.Functor;
import org.higherkindedj.hkt.Kind;
import org.higherkindedj.optics.Lens;

@AutoService(Processor.class)
@SupportedAnnotationTypes("org.higherkindedj.optics.annotations.GenerateLenses")
@SupportedSourceVersion(SourceVersion.RELEASE_24) // Updated to match your project
public class LensProcessor extends AbstractProcessor {

  @Override
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
    for (TypeElement annotation : annotations) {
      Set<? extends Element> annotatedElements = roundEnv.getElementsAnnotatedWith(annotation);
      for (Element element : annotatedElements) {
        if (element.getKind() != ElementKind.RECORD) {
          error("The @GenerateLenses annotation can only be applied to records.", element);
          continue;
        }
        try {
          generateLensesFile((TypeElement) element);
        } catch (IOException e) {
          error("Could not generate lenses file: " + e.getMessage(), element);
        }
      }
    }
    return true;
  }

  private void generateLensesFile(TypeElement recordElement) throws IOException {
    String recordName = recordElement.getSimpleName().toString();
    String packageName =
        processingEnv.getElementUtils().getPackageOf(recordElement).getQualifiedName().toString();
    String lensesClassName = recordName + "Lenses";

    TypeSpec.Builder lensesClassBuilder =
        TypeSpec.classBuilder(lensesClassName)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build());

    List<? extends RecordComponentElement> components = recordElement.getRecordComponents();
    ClassName recordClassName = ClassName.get(recordElement);

    for (RecordComponentElement component : components) {
      lensesClassBuilder.addMethod(createLensMethod(component, recordClassName, components));
    }

    JavaFile javaFile =
        JavaFile.builder(packageName, lensesClassBuilder.build())
            .addFileComment("Generated by hkj-optics-processor. Do not edit.")
            .build();

    javaFile.writeTo(processingEnv.getFiler());
  }

  private MethodSpec createLensMethod(
      RecordComponentElement component,
      ClassName recordClassName,
      List<? extends RecordComponentElement> allComponents) {
    String componentName = component.getSimpleName().toString();
    TypeMirror componentType = component.asType();
    TypeName componentTypeName = TypeName.get(componentType);

    ParameterizedTypeName lensTypeName =
        ParameterizedTypeName.get(
            ClassName.get(Lens.class), recordClassName, componentTypeName.box());

    TypeSpec lensImpl =
        TypeSpec.anonymousClassBuilder("")
            .addSuperinterface(lensTypeName)
            .addMethod(
                MethodSpec.methodBuilder("get")
                    .addAnnotation(Override.class)
                    .addModifiers(Modifier.PUBLIC)
                    .addParameter(recordClassName, "source")
                    .returns(componentTypeName.box())
                    .addStatement("return source.$L()", componentName)
                    .build())
            .addMethod(
                MethodSpec.methodBuilder("set")
                    .addAnnotation(Override.class)
                    .addModifiers(Modifier.PUBLIC)
                    .addParameter(componentTypeName.box(), "newValue")
                    .addParameter(recordClassName, "source")
                    .returns(recordClassName)
                    .addStatement(
                        "return new $T($L)",
                        recordClassName,
                        generateConstructorArgs(componentName, allComponents))
                    .build())
            .addMethod(createModifyFMethod(recordClassName, componentTypeName.box()))
            .build();

    return MethodSpec.methodBuilder(componentName)
        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
        .returns(lensTypeName)
        .addStatement("return $L", lensImpl)
        .build();
  }

  private String generateConstructorArgs(
      String changedComponent, List<? extends RecordComponentElement> allComponents) {
    return allComponents.stream()
        .map(
            c ->
                c.getSimpleName().toString().equals(changedComponent)
                    ? "newValue"
                    : "source." + c.getSimpleName() + "()")
        .collect(Collectors.joining(", "));
  }

  private MethodSpec createModifyFMethod(ClassName recordClassName, TypeName componentTypeName) {
    TypeVariableName fTypeVar = TypeVariableName.get("F");

    ParameterizedTypeName functionTypeName =
        ParameterizedTypeName.get(
            ClassName.get(Function.class),
            componentTypeName,
            ParameterizedTypeName.get(ClassName.get(Kind.class), fTypeVar, componentTypeName));

    return MethodSpec.methodBuilder("modifyF")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .addTypeVariable(fTypeVar)
        .returns(ParameterizedTypeName.get(ClassName.get(Kind.class), fTypeVar, recordClassName))
        .addParameter(functionTypeName, "f")
        .addParameter(recordClassName, "source")
        .addParameter(ParameterizedTypeName.get(ClassName.get(Functor.class), fTypeVar), "functor")
        .addStatement(
            "$T<$T, $T> fa = f.apply(get(source))", Kind.class, fTypeVar, componentTypeName)
        .addStatement("return functor.map(a -> set(a, source), fa)")
        .build();
  }

  private void error(String msg, Element e) {
    processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, msg, e);
  }
}
