// Copyright (c) 2025 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.optics.processing;

import com.google.auto.service.AutoService;
import com.palantir.javapoet.*;
import java.io.IOException;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.tools.Diagnostic;
import org.higherkindedj.optics.Prism;

@AutoService(Processor.class)
@SupportedAnnotationTypes("org.higherkindedj.optics.annotations.GeneratePrisms")
@SupportedSourceVersion(SourceVersion.RELEASE_24)
public class PrismProcessor extends AbstractProcessor {

  @Override
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
    for (TypeElement annotation : annotations) {
      for (Element element : roundEnv.getElementsAnnotatedWith(annotation)) {
        if (element.getKind() != ElementKind.INTERFACE && element.getKind() != ElementKind.ENUM) {
          error(
              "The @GeneratePrisms annotation can only be applied to sealed interfaces or enums.",
              element);
          continue;
        }
        try {
          generatePrismsFile((TypeElement) element);
        } catch (IOException e) {
          error("Could not generate prisms file: " + e.getMessage(), element);
        }
      }
    }
    return true;
  }

  private void generatePrismsFile(TypeElement sumTypeElement) throws IOException {
    String sumTypeName = sumTypeElement.getSimpleName().toString();
    String packageName =
        processingEnv.getElementUtils().getPackageOf(sumTypeElement).getQualifiedName().toString();
    String prismsClassName = sumTypeName + "Prisms";

    TypeSpec.Builder prismsClassBuilder =
        TypeSpec.classBuilder(prismsClassName)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build());

    // Handle Sealed Interfaces
    if (sumTypeElement.getModifiers().contains(Modifier.SEALED)) {
      for (var permittedSubclass : sumTypeElement.getPermittedSubclasses()) {
        var subtypeElement =
            (TypeElement) processingEnv.getTypeUtils().asElement(permittedSubclass);
        prismsClassBuilder.addMethod(createPrismMethodForSubtype(sumTypeElement, subtypeElement));
      }
    }
    // Handle Enums
    else if (sumTypeElement.getKind() == ElementKind.ENUM) {
      List<VariableElement> enumConstants =
          sumTypeElement.getEnclosedElements().stream()
              .filter(e -> e.getKind() == ElementKind.ENUM_CONSTANT)
              .map(VariableElement.class::cast)
              .collect(Collectors.toList());

      for (VariableElement enumConstant : enumConstants) {
        prismsClassBuilder.addMethod(createPrismMethodForEnum(sumTypeElement, enumConstant));
      }
    }

    JavaFile.builder(packageName, prismsClassBuilder.build())
        .addFileComment("Generated by hkj-optics-processor. Do not edit.")
        .build()
        .writeTo(processingEnv.getFiler());
  }

  private MethodSpec createPrismMethodForSubtype(TypeElement sumType, TypeElement subtype) {
    String methodName = toCamelCase(subtype.getSimpleName().toString());
    ClassName sumTypeName = ClassName.get(sumType);
    ClassName subTypeName = ClassName.get(subtype);

    ParameterizedTypeName prismTypeName =
        ParameterizedTypeName.get(ClassName.get(Prism.class), sumTypeName, subTypeName);

    TypeSpec prismImpl =
        TypeSpec.anonymousClassBuilder("")
            .addSuperinterface(prismTypeName)
            .addMethod(
                MethodSpec.methodBuilder("getOptional")
                    .addAnnotation(Override.class)
                    .addModifiers(Modifier.PUBLIC)
                    .addParameter(sumTypeName, "source")
                    .returns(ParameterizedTypeName.get(ClassName.get(Optional.class), subTypeName))
                    .addStatement(
                        "return source instanceof $T ? $T.of(($T) source) : $T.empty()",
                        subTypeName,
                        Optional.class,
                        subTypeName,
                        Optional.class)
                    .build())
            .addMethod(
                MethodSpec.methodBuilder("build")
                    .addAnnotation(Override.class)
                    .addModifiers(Modifier.PUBLIC)
                    .addParameter(subTypeName, "value")
                    .returns(sumTypeName)
                    .addStatement("return value")
                    .build())
            .build();

    return MethodSpec.methodBuilder(methodName)
        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
        .returns(prismTypeName)
        .addStatement("return $L", prismImpl)
        .build();
  }

  private MethodSpec createPrismMethodForEnum(TypeElement enumType, VariableElement enumConstant) {
    String methodName = toCamelCase(enumConstant.getSimpleName().toString());
    ClassName enumClassName = ClassName.get(enumType);

    ParameterizedTypeName prismTypeName =
        ParameterizedTypeName.get(ClassName.get(Prism.class), enumClassName, enumClassName);

    TypeSpec prismImpl =
        TypeSpec.anonymousClassBuilder("")
            .addSuperinterface(prismTypeName)
            .addMethod(
                MethodSpec.methodBuilder("getOptional")
                    .addAnnotation(Override.class)
                    .addModifiers(Modifier.PUBLIC)
                    .addParameter(enumClassName, "source")
                    .returns(
                        ParameterizedTypeName.get(ClassName.get(Optional.class), enumClassName))
                    .addStatement(
                        "return source == $T.$L ? $T.of(source) : $T.empty()",
                        enumClassName,
                        enumConstant.getSimpleName(),
                        Optional.class,
                        Optional.class)
                    .build())
            .addMethod(
                MethodSpec.methodBuilder("build")
                    .addAnnotation(Override.class)
                    .addModifiers(Modifier.PUBLIC)
                    .addParameter(enumClassName, "value")
                    .returns(enumClassName)
                    .addStatement("return value")
                    .build())
            .build();

    return MethodSpec.methodBuilder(methodName)
        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
        .returns(prismTypeName)
        .addStatement("return $L", prismImpl)
        .build();
  }

  // Handles both
  // PascalCase (like ShippingError) and SNAKE_CASE (like an enum constant).
  private static String toCamelCase(String s) {
    if (s == null || s.isEmpty()) {
      return s;
    }

    // Handle SNAKE_CASE (like an enum constant MY_ERROR)
    if (s.contains("_")) {
      String[] parts = s.split("_");
      StringBuilder camelCaseString = new StringBuilder(parts[0].toLowerCase());
      for (int i = 1; i < parts.length; i++) {
        if (!parts[i].isEmpty()) {
          camelCaseString
              .append(parts[i].substring(0, 1).toUpperCase())
              .append(parts[i].substring(1).toLowerCase());
        }
      }
      return camelCaseString.toString();
    }

    // Handle PascalCase (like a class name ShippingError)
    if (Character.isUpperCase(s.charAt(0))) {
      return Character.toLowerCase(s.charAt(0)) + s.substring(1);
    }

    return s;
  }

  private void error(String msg, Element e) {
    processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, msg, e);
  }
}
